### ISSUE TITLE
Guild View Hangs When No Runs Are Found - Crashes Chrome Browser

### ISSUE THREAD

**Issue by cfregly** [guildai/guildai#10]
shows spinning progress thingie, then crashed my browser

**Comment by gar1t** [comment]
@cfregly could you provide the output of `guild check` so I can work to reproduce this?

**Comment by gar1t** [comment]
Nevermind the version info, I was able recreate. Look for a fix in the next dev release (0.3.1.dev4).

**Comment by cfregly** [comment]
@gar1t  is this fixed?  i have a workaround, so i haven't seen this since i first created the issue.  i can try to test it later today.

**Comment by gar1t** [comment]
This should be fixed but I'd love to get a +1 from you, at which point we can close!

**Comment by gar1t** [comment]
Closing for now. If this shows up we can reopen.
