### ISSUE TITLE
strict scikit-learn version constraint

### ISSUE THREAD

**Issue by bo5o** [guildai/guildai#100]
Hi,

I started playing around with guildai for some time and was generally pleased and find it a great tool.
 
However, I have found that it has a pretty strict version constraint on scikit-learn, which is of course heavily used in other AI projects as well. In a lot of my projects I have tried guildai an ran into version conflicts, which I had to work around by upgrading/downgrading some other packages and even one project where I couldn't resolve a conflict.

Is there any reason why the scikit-learn dependency has to be so strict? Or can this be loosened?

**Comment by gar1t** [comment]
Timely - I just committed a fix for this yesterday! There's no good reason and the restriction hereby officially lifted :)

Look for a new rc (pre-release) in the next couple days. I'm working through some of these others issues in prep for 0.7 release.

In the meantime, you can upgrade manually to `pip` to the latest version of `scikit-learn`.

**Comment by bo5o** [comment]
Thanks a lot.

Now I see it in the commit history :) Nevermind me asking ..

**Comment by gar1t** [comment]
The fix is now generally available in 0.7.0. If this is still an issue, please re-open and we'll sort it out. Thanks again for the report.
