### ISSUE TITLE
Remove explicit check for AWS environment variables

### ISSUE THREAD

**Issue by tbelhalfaoui** [guildai/guildai#102]
I have some trouble using `guild pull s3` while being ssh-ed on en EC2 machine.
Guild keeps asking for `AWS_ACCESS_KEY_ID`, but it is not needed, since aws-cli grants access automatically through aws permissions.
Indeed, `aws s3 ls` works just fine, without any `AWS_` environment variables set.

And this simple boto code also works:
```
import boto3
s3 = boto3.client('s3')
s3.list_buckets()
```

I suspect there is an unnecessary manual check in guild for the env vars being set, that should be removed.
One should instead check the output of the aws command, and only if it fails, check the environment variables do display a nice error message.

**Comment by vinny1575** [comment]
Agree with this, would love to just have Guild utilize the credentials stored when the AWS CLI is setup.

**Comment by gar1t** [comment]
This is fixed in master and will be available in 0.7.0.rc10.

**Comment by gar1t** [comment]
The fix is now generally available in 0.7.0. If this is still an issue, please re-open and we'll sort it out. Thanks again for the report.
