### ISSUE TITLE
Run multiple stepped runs in parallel

### ISSUE THREAD

**Issue by wheatdog** [guildai/guildai#107]
It would be helpful to provide a way reliably run multiple stepped runs in parallel.

**Comment by gar1t** [comment]
Thank you for the suggestion!

When you say stepped here, are you talking about running multiple parent runs in parallel, or running the child runs in parallel?

E.g.

``` yaml
parent:
  steps:
   - child-1
   - child-2
```

Do you want to be able to run child-1 and child-2 in parallel in this case? Or multiple runs of parent?

**Comment by wheatdog** [comment]
Hi @gar1t , thanks for asking. My use case is to run multiple runs of parent in parallel.

**Comment by gar1t** [comment]
I don't know if this satisfies your goals, but I wrote up an example that I think accomplishes what you're looking for:

https://github.com/guildai/guildai/tree/master/examples/parallel-runs

Running the stepped operation with a queue doesn't work in rc9 but will in rc10.

Queues were initially experimental but they seem to work pretty well. If you have any thoughts good or bad, please feel free to share them here for the record. I'm very happy to make changes!

If we feel this first pass satisfies the goal, we can close this out and open new issues for specific new improvements to track those better.

**Comment by wheatdog** [comment]
I think this example is good for now. Thanks, @gar1t.

**Comment by gar1t** [comment]
I'm going to close this issue. We have a general category of improved hardware utilization for ongoing work. Better and easier parallel runs is part of that. Look for those issues to land. Would be great to get your input.
