### ISSUE TITLE
Add a guild logs command

### ISSUE THREAD

**Issue by tbelhalfaoui** [guildai/guildai#110]
When running with `--background` flag, one often needs to see the logs written to stdout.
Afaik, the only options are:
* Use `guild view` nice output,
* Tail the output manually: `tail -f venv/.guild/runs/<hash>/.guild/output`

It would be handy to have a `guild logs <run_id>` command, that would basically do the same as `tail -f`.

**Comment by gar1t** [comment]
Guild has a `watch` command that does this.

By default `watch` will tail the output of the latest running run. You can alternatively specify the run index or ID.

**Comment by tbelhalfaoui** [comment]
Somehow I missed this `watch` option... It is indeed exactly what I meant!
Sorry about that.
