### ISSUE TITLE
Is it possible to infer parameters from files in config?

### ISSUE THREAD

**Issue by lambdaofgod** [guildai/guildai#116]
In the [basic example](https://guild.ai/docs/start/) you showed that guild is able to infer x from the script. Is it possible to do this automatically for running stuff from configuration?
I've written a config file for my example, because I need to use a file, but now when I run I don't get message for passing in argument which was present when running a script.

**Comment by gar1t** [comment]
We recently modified Guild to no longer automatically import flags. You now need to explicitly import flags or define them outright in the Guild file.

This is what you want:

``` yaml
train:
  flags-import: all
```

You can alternatively list the flags you want to import:

``` yaml
train:
  flags-import:
    - x
```
