### ISSUE TITLE
Caching Bayesian optimization parameters

### ISSUE THREAD

**Issue by lambdaofgod** [guildai/guildai#117]
Is it possible to restart Bayesian optimizer using information from previous runs?

Did you ever think of adding this feature? It seems like it could be very useful.

If you think it could be in principle achieved I'd be happy to help - could you estimate how much work would it take and provide some guidance?

**Comment by gar1t** [comment]
Guild supports this - in fact someone else just asked about this here:

https://github.com/guildai/guildai/issues/115

I'll make sure this topic is covered in the updated docs.
