### ISSUE TITLE
Guild messing with sys.path (Module not found)/deep module dependencies + proper guild.yml setup

### ISSUE THREAD

**Issue by jukiewiczm** [guildai/guildai#118]
I have the following project structure
```
-- root
  -- data
    -- train.csv
    -- test.csv
  -- modeling
    -- model_validation.py
    -- models
       -- rnn
         -- torch_rnn_net.py
         -- rnn_tuning_guild.py
         -- guild.yml
  -- other_module
     -- something.py
```

I'm trying to tune my model by running `rnn_tuning_guild.py` file. I'm basically using everything I have in the project within this file (like train.csv/test.csv, model_validation.py, torch_rnn_net.py).
I run the script from the `root/modeling/models/rnn` path. Obviously, this created some importing errors. Therefore, what I did to overcome that is the following three lines on top of `rnn_tuning_guild.py` file:
```
import sys
project_root_path = "absolute_path_to_root"
sys.path.append(project_root_path)
```
I added the project_root_path as a parameter in `guild.yml` to make it configurable.
This worked fine in guild version `0.6.6` and works fine when running the script directly with python, but for some reason this doesn't work anymore with guild `0.7.0rc4`. Funnily enough, some modules import just fine (like `other_module.something`), but it doesn't find the `modeling.models.rnn.torch_rnn_net` module for some reason. The only difference I can see is that it's the most deeply nested module, but theoretically it shouldn't make any difference (all the modules have proper __init__.py files).

Is this a bug? Am I missing something?
On the other hand, I can imagine the `sys.path` trick might not be the proper way to get it done and this can be somehow resolved with a nicely configured `guild.yml` file. I had some tries with the `sourcecode` parameter but no luck (it still doesn't see the module).

I'd like to keep the `guild.yml` file together with `rnn_tuning_guild.py` where they are if possible.

How to solve this?

To give you some more context, there are the files I'm talking about:
https://github.com/jukiewiczm/kaggle-predict-future-sales/tree/implement-guild-tuning/modeling/models/rnn

**Comment by gar1t** [comment]
Here's a sample Guild file for your project - it just runs a test op that prints a message.

https://github.com/gar1t/kaggle-predict-future-sales/commit/6a0b952ae0a55ae05a3d06eb3ef725af92349f06

A few points:

- Note the spelling of `main` in the Guild file - it uses a combination of a path-like syntax along with the standard Python dot-syntax when referencing modules. The path part tells Guild to include `modeling` in the system path.

- Your project layout is advanced enough to warrant a `sourcecode` spec. If your script needs any other modules, just add their directories there.

In general, Guild doesn't require that you create a Guild-specific wrapper. In theory, Guild config can wrap any standard Python script. Sometimes you might get stuck with config and just use a wrapper - that's fine. But chances are you can just tweak your config (`guild.yml`) to get things working.

Admittedly, some of this config stuff is hard to sort out. I'm happy to help fix things though via PRs if you like.

**Comment by jukiewiczm** [comment]
@gar1t 
Thanks for the quick answer.
I know guild doesn't require a custom wrapper, but I didn't really have all-in-one tuning script anyway, that's why I created it.

I now get the idea on how to configure that properly, but would that be possible for the `guild.yml` file being in `root/modeling/models/rnn` folder? It doesn't seem to work with absolute paths or relative `../../` paths. Does the `guild.yml` net to be in top level for this to work?

**Comment by gar1t** [comment]
Here's an example of that configuration:

https://github.com/gar1t/kaggle-predict-future-sales/blob/master/modeling/models/rnn/guild.yml

Please upgrade to `0.7.0.rc5` as it has a fix you'll need.

**Comment by jukiewiczm** [comment]
You rock man. Thanks a lot!
