### ISSUE TITLE
`guild install mnist` requires `--pre` even though `pip install guildai` does not require `--pre` (0.3.1.rc1)

### ISSUE THREAD

**Issue by cfregly** [guildai/guildai#13]
```
guild install -U mnist --pre
```
```
Collecting gpkg.mnist
Downloading gpkg.mnist-0.3.1.dev3-py2.py3-none-any.whl
Installing collected packages: gpkg.mnist
Successfully installed gpkg.mnist-0.3.1.dev3
```

**Comment by gar1t** [comment]
Are you seeing docs that specify a `--pre` option when installing packages?

`--pre` is not required when installing Guild packages. You'd use that whenever you have a pre-release version of Guild. The `rc1` release btw is considered a pre-release version.

**Comment by cfregly** [comment]
it fails while installing an older guild package.

i’ve been using ‘—pre’ to keep things from breaking.

(i don’t like this pre stuff, btw)

**Comment by gar1t** [comment]
As a rule, pre-release versions of Guild should use pre-release version of packages. This scheme lets us publish routine updates without breaking stable releases. It's baked into setuptools, pip, and PyPI and seems to work overall for users. E.g. TensorFlow is currently 1.7.0rc1 on PyPI, but you'll get 1.6.0 if you install without `--pre`.

Let me know if you spot something misleading in the docs and I'll update!

**Comment by cfregly** [comment]
the original issue is still an issue.

stated differently:

i don't have to specify --pre to install guildai .rc1, however, i still have to specify --pre to install the models that work with the (non --pre) guildai.

this is confusing.  i fully understand the concept of --pre, but it's being used inconsistently.  

--pre was being used properly a few days ago - before you release rc1 (which no longer requires --pre)

if i don't specify --pre for the guild install mnist, it pulls in a super-old mist - and fails.

**Comment by gar1t** [comment]
I just ran `pip install guildai` without `--pre` and I got `0.3.0`. Could you provide the details on the command you're running where you are not using `--pre` but are getting `0.3.1rc1`? That's a bug somewhere.

**Comment by cfregly** [comment]
the best way to catch these types of things is to incorporate a Docker build from a bare-bones install of Ubuntu (or whatever) into your CI.  otherwise, you will always be subject to environment skew.

i deal with this every single day - and the only thing that's made a difference is using a fresh Docker build for every build.

here is the relevant output from my Docker build that shows `--pre` is not needed for 0.3.1.rc1:
```
Step 1/21 : FROM pipelineai/ubuntu-16.04-cpu:1.5.0
 ---> 0ff7cafc7bf5
Step 2/21 : WORKDIR /root
 ---> Using cache
 ---> 95b4e2f574f8
Step 3/21 : RUN   apt-get install -y build-essential   && curl -sL https://deb.nodesource.com/setup_9.x | bash -   && apt-get install -y nodejs
 ---> Using cache
 ---> 3468124ebb2c
Step 4/21 : RUN   apt-get install -y --no-install-recommends libav-tools   && apt-get clean
 ---> Using cache
 ---> 037166f37382
Step 5/21 : RUN   npm install -g configurable-http-proxy && rm -rf ~/.npm
 ---> Using cache
 ---> e03d06feec8d
Step 6/21 : RUN   mkdir -p /root/logs
 ---> Using cache
 ---> db0c03ce2539
Step 7/21 : ENV   LOGS_HOME=/root/logs
 ---> Using cache
 ---> a286ccb3b442
Step 8/21 : COPY sysutils/ sysutils/
 ---> Using cache
 ---> 4ce768fef3af
Step 9/21 : RUN   pip install -U --ignore-installed --no-cache guildai==0.3.1.rc1
 ---> Running in 47f5555bc3a6
Collecting guildai==0.3.1.rc1
  Downloading guildai-0.3.1rc1-cp36-cp36m-manylinux1_x86_64.whl (5.6MB)
Collecting six (from guildai==0.3.1.rc1)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting Whoosh (from guildai==0.3.1.rc1)
  Downloading Whoosh-2.7.4-py2.py3-none-any.whl (468kB)
Collecting PyYAML (from guildai==0.3.1.rc1)
  Downloading PyYAML-3.12.tar.gz (253kB)
Collecting Werkzeug (from guildai==0.3.1.rc1)
  Downloading Werkzeug-0.14.1-py2.py3-none-any.whl (322kB)
Collecting chardet (from guildai==0.3.1.rc1)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting setuptools (from guildai==0.3.1.rc1)
  Downloading setuptools-39.0.1-py2.py3-none-any.whl (569kB)
Collecting tabview (from guildai==0.3.1.rc1)
  Downloading tabview-1.4.3-py2.py3-none-any.whl
Collecting python-dateutil (from guildai==0.3.1.rc1)
  Downloading python_dateutil-2.7.2-py2.py3-none-any.whl (212kB)
Collecting twine (from guildai==0.3.1.rc1)
  Downloading twine-1.11.0-py2.py3-none-any.whl
Collecting pip (from guildai==0.3.1.rc1)
  Downloading pip-9.0.3-py2.py3-none-any.whl (1.4MB)
Collecting pkginfo>=1.4.2 (from twine->guildai==0.3.1.rc1)
  Downloading pkginfo-1.4.2-py2.py3-none-any.whl
Collecting requests!=2.15,!=2.16,>=2.5.0 (from twine->guildai==0.3.1.rc1)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
Collecting tqdm>=4.14 (from twine->guildai==0.3.1.rc1)
  Downloading tqdm-4.19.9-py2.py3-none-any.whl (52kB)
Collecting requests-toolbelt>=0.8.0 (from twine->guildai==0.3.1.rc1)
  Downloading requests_toolbelt-0.8.0-py2.py3-none-any.whl (54kB)
Collecting certifi>=2017.4.17 (from requests!=2.15,!=2.16,>=2.5.0->twine->guildai==0.3.1.rc1)
  Downloading certifi-2018.1.18-py2.py3-none-any.whl (151kB)
Collecting idna<2.7,>=2.5 (from requests!=2.15,!=2.16,>=2.5.0->twine->guildai==0.3.1.rc1)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
Collecting urllib3<1.23,>=1.21.1 (from requests!=2.15,!=2.16,>=2.5.0->twine->guildai==0.3.1.rc1)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
Installing collected packages: six, Whoosh, PyYAML, Werkzeug, chardet, setuptools, tabview, python-dateutil, pkginfo, certifi, idna, urllib3, requests, tqdm, requests-toolbelt, twine, pip, guildai
  Running setup.py install for PyYAML: started
    Running setup.py install for PyYAML: finished with status 'done'
Successfully installed PyYAML-3.12 Werkzeug-0.14.1 Whoosh-2.7.4 certifi-2018.1.18 chardet-3.0.4 guildai-0.3.1rc1 idna-2.6 pip-9.0.3 pkginfo-1.4.2 python-dateutil-2.7.2 requests-2.18.4 requests-toolbelt-0.8.0 setuptools-39.0.1 six-1.11.0 tabview-1.4.3 tqdm-4.19.9 twine-1.11.0 urllib3-1.22
Removing intermediate container 47f5555bc3a6
```

**Comment by gar1t** [comment]
You're getting rc1 because you're explicitly asking for it:

    pip install -U --ignore-installed --no-cache guildai==0.3.1.rc1

You can similarly specify a requirement when installing a Guild package:

    guild install mnist=0.3.1.dev1

or use `--pre`, which will grab the latest.

**Comment by gar1t** [comment]
For the record, Guild uses Docker for builds and test on Linux. Here's our CI config:

https://github.com/guildai/guild/blob/master/.circleci/config.yml

Each release that makes it to PyPI as a distribution is built on a new environment and passes our test suite.

The CI status is on the GitHub README:

https://github.com/guildai/guild

You can also get the blow-by-blow on the Circle CI page directly:

https://circleci.com/gh/guildai/guild

We'll continue to make pre-releases available on PyPI, like many other distributions in Python. Those may introduce backward incompatible changes with packages though that's obviously not ideal and we'll try to avoid them wherever possible! If you'd prefer to avoid the potential volatility that comes with early releases (very understandable) avoid the '.dev' and '.rc' suffixes.

If you do get a pre-release version without explicitly asking for it (by either using `--pre` or by explicitly installing a pre-release version as above) that's a bug.

We can look at other ways of preventing these irritating breakages (my apologies for that!) in a more formal versioning checking scheme (this would be internal to Guild). But as this is a 0.3 product (not 3.0) things like this are bound to happen along the way. Your best bet may be to wait for stable releases.
