### ISSUE TITLE
Assumed ARCHIVE was referring to a tarball for guild import

### ISSUE THREAD

**Issue by Jim-Holmstroem** [guildai/guildai#132]
Got some runs exported to be by colleagues (as .tar.gz since that's how you distribute folders) and tried to import them with `guild import`
https://guild.ai/docs/commands/import-cmd/

Figured out how it worked so that's not the issue, but the documentation might be revised to not need to understand export.
Might be as simple as copying some of the words used in export :)

Also `guild: directory 'somethash.tar.gz' does not exist` gave me a hint on what was happening, but the message is kinda confusing. Perhaps something along the lines of `guild: guild import expects a directory`

**Comment by Jim-Holmstroem** [comment]
also not clear from documentation that you need to have an exported run in a folder and run `guild import folder` and it goes in and finds a run folder inside on that folder

**Comment by gar1t** [comment]
Sorry for the confusion! The next release has the following fixes to address your points:

- Improved help text in `guild import --help`
- Improved error messages and error checks in import command

See 0fc91785

Thanks for the report!

**Comment by gar1t** [comment]
The fix is now generally available in 0.7.0. If this is still an issue, please re-open and we'll sort it out. Thanks again for the report!
