### ISSUE TITLE
Remote into a Docker container

### ISSUE THREAD

**Issue by stephenhermes** [guildai/guildai#138]
Is it possible to run runs remotely into a Docker container? For example, if I have a remote GPU server which is running a Docker container (e.g., `tensorflow/tensorflow:latest-gpu`) is it possible to launch a run from my local machine and have it run in the containerized environment?

**Comment by gar1t** [comment]
It's possible to implement that yourself, but not something out-of-the-box from Guild. Guild packages the run as a set of files and installs them per run - so you get a full copy of the requirements, but not as a container.

**Comment by stephenhermes** [comment]
Sorry, my question was unclear. I mean is it possible (out-of-the-box-ish) to have Guild package a run as it does already, but install the files in an already existing (and running) Docker container?

**Comment by gar1t** [comment]
Ah, yes very possible :) If you can connect to said contained over ssh Guild should have no problem running runs on it. You'd configure it using the same method as a standard ssh based remote.

**Comment by stephenhermes** [comment]
Great news. Thanks!
