### ISSUE TITLE
guild train mnist:cnn fails when building with a Docker image - always hangs at Step 20

### ISSUE THREAD

**Issue by cfregly** [guildai/guildai#14]
i tried to increase the RAM allocated to the image, but it always fails at the same step.

note:  mnist:softmax works fine.

**Comment by gar1t** [comment]
@cfregly Could you point me to the Dockerfile you're using so I can attempt to recreate this?

**Comment by gar1t** [comment]
Closing for lack of followup. Please feel free to reopen if needed.
