### ISSUE TITLE
Unhelpful error message when main spec ends in .py

### ISSUE THREAD

**Issue by lambdaofgod** [guildai/guildai#149]
I have a python file which resides in a subdirectory

```
foo:
  -train.py
```

How to make an operation that uses that file?
When I specify

`main: foo/train.py`

It gives

`guild: No module named training.py`

I also tried to manipulate `sourcecode` (adding root) but to no avail. What is `sourcecode` supposed to mean anyway? I have trouble finding this on documentation webpage

**Comment by gar1t** [comment]
You want `foo/train` there. Main specs should not end in `.py`.

Guild should give you an intelligible message there - I think that's worthy of a bug classification. Though we should update the issue title to something like "Unhelpful error message when main spec ends in `.py`". @lambdaofgod I'll leave that to you - but I'll mark this as a bug in any case.
