### ISSUE TITLE
No module name `vcs.git` and `pip.vcs` when building guild from source

### ISSUE THREAD

**Issue by cfregly** [guildai/guildai#15]
New errors just started showing up.  are you seeing these, @gar1t ?

Not sure what changed.  I'm on the new pip 10.0, but i was also having this issue under pip 9.0.3, i believe.

Python2
```
$ python2 setup.py build
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    from pip.vcs.git import Git
ImportError: No module named vcs.git
make: *** [build] Error 1
```

Python3
```
$ python3 setup.py build
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    from pip.vcs.git import Git
ModuleNotFoundError: No module named 'pip.vcs'
```

**Comment by cfregly** [comment]
Possibly related to pip 10.0.0's newly-_internal'ized apis described here (but i think i was having the issue in 9.0.3, but maybe not):

https://github.com/pypa/pip/blob/28f3ce6fe2144c213d253e4d0a27ad4334611419/NEWS.rst

**Comment by cfregly** [comment]
ok, confirmed that this is, indeed, a pip 10.0.0-specific issue.

workaround for now:  downgrade to pip 9.0.3 as follows:

python2
```
curl https://bootstrap.pypa.io/3.3/get-pip.py | python2 - 'pip==9.0.3'
```

python3
```
curl https://bootstrap.pypa.io/3.3/get-pip.py | python3 - 'pip==9.0.3'
```

i see that guild/requirements.txt specifies pip<=9.0, so this should take care of it.  not sure why it's not.

i'm not calling "pip install -r requirements.txt" before `python setup.py install`.

am i supposed to?

**Comment by cfregly** [comment]
should `setup.py` reference requirements.txt somehow?  through `install_requires` or some such?

**Comment by gar1t** [comment]
Should be building now (master). Thanks for the heads up!

**Comment by cfregly** [comment]
more info:

This is causing issues:
https://github.com/guildai/guild/blob/master/guildai.dist-info/METADATA#L32

this pulls in pip==10.0.0 because the version is not specified.

in other words, this METADATA file is conflicting with the requirements.txt which has all the nice versions specified.

Not sure if this is still an issue after your recent commits from earlier today, but it's worth highlighting.

**Comment by gar1t** [comment]
Closing as this should be resolved. pip support is now internal to Guild.
