### ISSUE TITLE
[question / enhancement] Continue batch run after error

### ISSUE THREAD

**Issue by thomsentner** [guildai/guildai#158]
Hi,
I do not seem to find an option to keep a batch run running following an error. Let's say I'm planning on running 12 combinations of conditions, but every other run results in an error. So far, such an error has stopped the whole guildai batch run for me. Is there any option I am missing, or would this only be possible when initiating a batch using bash? If so, I think this would be a nice feature to implement.

**Comment by gar1t** [comment]
Sorry for the late reply! You're right about the behavior - in 0.7.0.rc9 and earlier batch runs will stop early when one of their trials fails.

This behavior is changed in 0.7.0.rc10 - batch runs will continue to run by default even when a trial fails. There's a new `--fail-on-trial-error` flag option that causes the batch to fail as soon as trial fails.

rc10 will go out this week. Thanks for your patience!

**Comment by gar1t** [comment]
This should be fixed in 0.7.0. If you still see the behavior, please re-open. Thanks again for the report!
