### ISSUE TITLE
`guild/tests/samples/packages/gpkg/mnist/cnn.py` contains Python2-only print "" statements

### ISSUE THREAD

**Issue by cfregly** [guildai/guildai#16]
guild/tests/samples/packages/gpkg/mnist/cnn.py

should use print("") or contain __future__ workaround or equivalent.

this is failing my mypy scan (`pip install mypy`).

**Comment by gar1t** [comment]
Could you submit a PR?

**Comment by gar1t** [comment]
This is fixed. Thanks again!
