### ISSUE TITLE
Handle parents parser correctly

### ISSUE THREAD

**Issue by wheatdog** [guildai/guildai#164]
I use pytorch-lightning for my research. In pytorch-lightning, there is a convention that define arguments separately in `train.py` and `lightning_module.py`. This is achieved by defining two `argparse.ArgumentParser` and [using `parents` argument](https://docs.python.org/3.7/library/argparse.html#parents). You can check [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/basic_examples/gpu_template.py#L51-L75) and [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pl_examples/models/lightning_template.py#L258-L282) for example. 

The strange issue is that the arguments in `train.py` (parent parser) can't be detected by guild. Here is [an minimal example](https://github.com/wheatdog/guild-parent-parser).

After digging into guild source code, I found that [P_FLAGS in guild/plugins/import_argparse_flags_main.py](https://github.com/guildai/guildai/blob/master/guild/plugins/import_argparse_flags_main.py#L26) would have two keys: one for child parser and one for parent parser, and in `_write_flags_and_exit` it only uses the child parser. It should also check for its parent parser.

**Comment by wheatdog** [comment]
Same issue: #147

**Comment by gar1t** [comment]
Gold star report!

This should be resolve in 8fdf32c8.

**Comment by gar1t** [comment]
Issue resolution doc that uses @wheatdog code to reproduce:

https://github.com/guildai/issue-resolution/tree/master/164-handle-parents-parser-correctly

**Comment by gar1t** [comment]
Should be fixed in 0.7.0. If you're still seeing this behavior, please feel free to re-open. Thanks again!
