### ISSUE TITLE
artifact management

### ISSUE THREAD

**Issue by CarloLucibello** [guildai/guildai#169]
Hi,
I just discovered Guild and I'm loving it, thank you for creating it. 
Is there any way to store artifacts, e.g. model checkpoints, in the runs directory?
The website mentions "artifacts" in couple of spots but gives no indirection

**Comment by CarloLucibello** [comment]
Maybe this can be done by having `guild run` set a `GUILD_RUN_DIR` environment variable

**Comment by CarloLucibello** [comment]
A `RUN_DIR` env variable is already defined, so this issue could be simply solved by just adding a usage example to the documentation. 
One could also think about adding a specific directory for artifacts in the run directory, with the corresponding env variable. In that case one would just have to add the line
```python
savedir = os.environ.get("ARTIFACTS_DIR", "mydir")                                                                                                 
```
to a script to  get the appropriate directory

**Comment by gar1t** [comment]
To save a file to a run directory, all you have to do is write that file using a relative path. When Guild runs an operation, it creates a unique directory and uses it as the working directory for a run.

So this is enough to save a file named "hello.txt" as a run artifact:

``` python
with open("hello.txt", "w") as f:
    f.write("hi!")
```

When you run this with Guild, you'll get a run, which will be captured in a unique run directory. You can see what's in that directory various ways, the most common being:

```
$ guild ls [RUN]  # list files - you can omit RUN if it's the latest
$ guild open [RUN]  # open RUN directory in local file explorer - again omit RUN for latest
```

**Comment by CarloLucibello** [comment]
ok, that is perfectly satisfying, thanks
