### ISSUE TITLE
Incompatible with pip v10.0.1

### ISSUE THREAD

**Issue by Hoeze** [guildai/guildai#17]
"guild check", etc. does not work after installing pip v10.0.1.

How to reproduce:
1) Install Ubuntu 18.04 with python3-pip
2) run "sudo pip3 install --upgrade pip"
3) run "guild check"

**Comment by gar1t** [comment]
@Hoeze This is fixed in 0.3.2, which is in the process of making its way to PyPI. I'll update here once I've verified that 0.3.2 is good to go. Sorry for the issue!

**Comment by gar1t** [comment]
0.3.2 is now available on PyPI, so this should fix your issue:

    pip install --upgrade guildai

**Comment by Hoeze** [comment]
Thank you very much
