### ISSUE TITLE
[feature request] expand support for custom runs directories

### ISSUE THREAD

**Issue by CarloLucibello** [guildai/guildai#170]
Since we are already able to save runs in a custom directory using the `-d` or `--runs-dir`  flags as in
```
guild run -d mydir/  myscript.py
```
it would be nice to expand the support for this also in other commands. e.g. 
```
guild runs -d mydir/
guild view -d mydir/
guild tensorboard -d mydir/
```

**Comment by CarloLucibello** [comment]
When opening this issue I wasn't aware of the `-H` flag for setting guild's home. While not as flexible as the proposal above, this greatly alleviates the problem for me

**Comment by gar1t** [comment]
Yeah, I was going to suggest that - you can also define an environment variable `GUILD_HOME` to specify where runs are saved.

Guild really wants to manage the parent directory of runs - because it saves deleted runs, resources, and other cached data as well.

Saving runs to a custom directory using `--run-dir` places that run outside of Guild's management. This is typically done for staging/debug purposes.

**Comment by CarloLucibello** [comment]
> Saving runs to a custom directory using --run-dir places that run outside of Guild's management. This is typically done for staging/debug purposes.

yeah, but also when staging/debugging one may want to view/list runs, so maybe leaving this issue still make some sense, but feel free to close if this just adds noise.  

side note: I wish `-H` was the default behavior

**Comment by gar1t** [comment]
Setting the environment variable `GUILD_HOME` defines the `-H` option for every command implicitly. You can further override it using `-H` of course.

The behavior you're looking for, where runs are located in different locations - perhaps based on the project you're working on - is pretty common. Guild supports this using environments. It's often not just the runs location, but the set of installed Python packages that you want to control in various contexts. When you activate a virtual environment (created using conda, virtualenv, or venv) Guild, by default, uses Guild home in the environment.

So the workflow is to first activate an environment and then use Guild in some context.

I'm not sure if this might be something closer to what you're looking for - but I thought I'd highlight it as a common use pattern.

**Comment by CarloLucibello** [comment]
I do work in conda environments, but I share them among different projects. Also, this makes GUILD_HOME located in 
```
/home/carlo/miniconda3/envs/...
```
In the end,  I added to my .bashrc the alias
```
 alias g="-H ./"
```
and my workflow for any project would be:
```
cd myprojectdir                      # move to project dir
conda activate myenv            # activate environment
g run -d temp/ myscript.py     # while developing
g run myscript.py                   # save logs in runs/
g view
.... 
```
This was quite comfy for me once I got used to it.
Thanks for your help and for this nice tool
