### ISSUE TITLE
Guild compare with range selector > total of runs throws an error

### ISSUE THREAD

**Issue by MaximeChurin** [guildai/guildai#172]
When using `$ guild compare :x` with x a number of runs greater than `$ guild runs --all | wc -l`
We get the following output :
`guild: could not find a run matching ':X'
Try 'guild runs list' for a list.`

So when the range selector is greater then the total of runs, Guild treats it as a run id and throws an error. In case that is the correct behavior, the message should mention an index out of range cause.

**Comment by gar1t** [comment]
Thank you for the report! I agree this should be clearer.

**Comment by gar1t** [comment]
No longer an issue with 0.7
