### ISSUE TITLE
Is it possible to change the path defined by $RUN_DIR?

### ISSUE THREAD

**Issue by craston** [guildai/guildai#176]
Hi, great work  on guild and I find it very useful!
Currently, since I use a conda environment, my guild runs are stored in 
``path_conda_env/.guild/runs/${RUN_ID}``
Based on my understanding, this path is set by the $RUN_DIR environment variable. Is it possible to change the path defined by $RUN_DIR?

**Comment by CarloLucibello** [comment]
you can look at #170 for a related issue

**Comment by craston** [comment]
Perfect, that works! Thanks
