### ISSUE TITLE
resource 'slim/models-lib' required by operation 'slim-resnet-101:freeze' is not installed

### ISSUE THREAD

**Issue by Srini511** [guildai/guildai#18]
Hi I am trying to generate a frozen resnet-101 graph and i am getting the error below

guild: run failed because a dependency was not met: resource 'slim/models-lib' required by operation 'slim-resnet-101:freeze' is not installed

**Comment by gar1t** [comment]
Sorry for the delay. I've been working on getting 0.5 release.

So Guild has changed quite a bit from the version you're working on. Could you update to 0.5.1 (latest release) and check out the `gpkg.slim.models` package? That has the various models that you're probably interested in looking at.

**Comment by gar1t** [comment]
Closing as Slim packages are no longer supported.
