### ISSUE TITLE
Using an exponent as label raises error when filtering runs

### ISSUE THREAD

**Issue by casimp** [guildai/guildai#183]
If you use an exponent as a run label then guild compare/view/tensorboard will raise `TypeError: argument of type 'float' is not iterable` if you try to filter runs by label. 

```
- model: label_bug
  description: MWE for exponent label bug
  operations:
    train:
      main: guild.pass
```
If you then execute the train operation as follows:

`guild run train --label 1e6`

then any filtering by label:

`guild compare --label any_filter`

Will raise a TypeError, the final part of that traceback is:

```
  File "/home/dhalion-linux/miniconda3/envs/py3/lib/python3.6/site-packages/guild/var.py", line 138, in <genexpr>
    filter = lambda r: all((f(r) for f in filters))
  File "/home/dhalion-linux/miniconda3/envs/py3/lib/python3.6/site-packages/guild/commands/runs_impl.py", line 188, in f
    return any((l in run_label for l in labels))
  File "/home/dhalion-linux/miniconda3/envs/py3/lib/python3.6/site-packages/guild/commands/runs_impl.py", line 188, in <genexpr>
    return any((l in run_label for l in labels))
TypeError: argument of type 'float' is not iterable
```

Interestingly, if you explicitly use a float (which seems to be the source of the error) then there is no issue, i.e.:

`guild run train --label 1.0`

Doesn't raise any errors in guild compare.

**Comment by gar1t** [comment]
Should be fixed in 0.7.0. If you're still seeing this behavior, please feel free to re-open. Thanks again!
