### ISSUE TITLE
fail pip install guildai

### ISSUE THREAD

**Issue by lilly-chen** [guildai/guildai#19]
Hi, 

when I ust pip install guildai to install the package:

it gives me an error "Could not find a version that satisfies the requirement guildai (from versions: )
No matching distribution found for guildai"

How could I fix this?

Thanks!

**Comment by gar1t** [comment]
What do you see when you run:

    pip --verbose search guildai

**Comment by lilly-chen** [comment]
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "POST /pypi HTTP/1.1" 200 251
guildai (0.5.3)  - Toolkit to streamline TensorFlow™ and Keras deep learning.

**Comment by gar1t** [comment]
And finally, would you please run these two commands:

```
pip --version
uname -a
```

If by chance you're running on Mac with Python 3.7, are you able to install tensorflow? From what I'm seeing, TF is still not available on 3.7 for Mac [1]

[1] https://github.com/tensorflow/tensorflow/issues/17022

**Comment by lilly-chen** [comment]
pip --version
pip 18.1 from c:\users\chenl\anaconda3\envs\dand\lib\site-packages\pip (python 2.7)

**Comment by lilly-chen** [comment]
uname -a
'uname' is not recognized as an internal or external command,
operable program or batch file.

**Comment by gar1t** [comment]
Unfortunately Windows is not supported in 0.5. This will be added in an upcoming release.

In the meantime, you can run Guild in a virtual machine with a Linux OS on Windows.

**Comment by gar1t** [comment]
Closing this as Windows is now supported (0.6.3). If you're still seeing this error, please open a new issue with your system details. You can use https://github.com/gar1t/check-pip-install to get a detailed report that will help us troubleshoot the issues.

**Comment by brunofms** [comment]
Same issue here, although it is a MacOS:

$ pip install --user guildai
ERROR: Could not find a version that satisfies the requirement guildai (from versions: none)
ERROR: No matching distribution found for guildai

$ pip --verbose search guildai
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "POST /pypi HTTP/1.1" 200 247
guildai (0.6.6)  - Toolkit to automate and optimize machine learning model development

$ uname -a
Darwin iMac 16.7.0 Darwin Kernel Version 16.7.0: Sun Jun  2 20:26:31 PDT 2019; root:xnu-3789.73.50~1/RELEASE_X86_64 x86_64
