### ISSUE TITLE
Support AWS named profiles for remotes

### ISSUE THREAD

**Issue by igrinis** [guildai/guildai#191]
When working simultaneously with multiple accounts for AWS named profiles becomes a necessity. Currently Guild only supports AWS credentials through environmental variables. I suggest adding a new attribute `profile` to the that will replace the need for external environmental variables. It will increase security and make more clear which account is used for the remote.

**Comment by gar1t** [comment]
Are you talking about named profiles for the AWS CLI?

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

Also, #102 should enable you to configure your env at least with defaults that would apply.

I realize that's not what you're asking for - but I mention it in case it would help your workflow at all.

**Comment by igrinis** [comment]
Yes, I meant profiles for the AWS CLI. 

Ability to use default profile is already a real enabler. The upcoming release will probably answer most of my requirements. Thank you very much for you work!!

**Comment by gar1t** [comment]
Just revisiting this issue. With 0.7.0 out you should be able to setup an environment that uses the named profile. I realize that work situations change and you might not be into this stuff atm but if you spot any issues let me know.

**Comment by igrinis** [comment]
Can you clarify, with 0.7 the named profile feature is implemented? If so, what is the setting name to use the option?

I'm slowly pushing Guild in our group, and the feedback is very positive.

**Comment by gar1t** [comment]
From what I'm seeing [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html) using a named profile is supported by defining the `AWS_PROFILE` environment variable after having configured the profile with the AWS CLI.

Guild should let these environment variables pass through when running AWS commands, allowing the AWS CLI to handle auth, etc. as it would if you called the AWS CLI directly.

Prior to 0.7 Guild complained (exited with an error message) when certain `AWS_XXX` auth variables weren't set. This has been removed to let you use other auth schemes. I.e. Guild is getting out of the way to let the AWS CLI work as it wants to.

If this doesn't work for you - i.e. following the steps to configure the profile and setting with `AWS_PROFILE` as an environment variable - we'll need to figure out what's not working.

**Comment by igrinis** [comment]
Works smoothly. Great work!!!
