### ISSUE TITLE
Docs search provides broken links

### ISSUE THREAD

**Issue by bentaculum** [guildai/guildai#194]
The results of many search queries on the [docs site](https://guild.ai/docs/) point to broken links, e.g. the first three search results for _config_.

**Comment by gar1t** [comment]
Thank you! Yes that's a major issue - that index is pointing to the wrong content! This will be fixed when 0.7 goes live. We'll need to correctly isolate dev index from production in the future.

**Comment by gar1t** [comment]
Fixed since move to Discourse.
