### ISSUE TITLE
Random search with grid

### ISSUE THREAD

**Issue by MislavSag** [guildai/guildai#199]
I read in the documentation that it is possible to use manual/grid search and random search. In docs, it says that I use random search if I use the uniform function in at least one variable. But is it possible to use a random search on a grid?

For example, if I want to run guild run train `x=[1,2,3,4]`, but want that method randomly choose 2 models (e.g. 2 and 4). Is it possible to do that?

**Comment by gar1t** [comment]
Yes, in your example you'd run this:

    $ guild run train x=[1,2,3,4] -o random -m 2

This explicitly tells Guild to use the `random` optimizer and limits the number of trials to 2.

Note that you might end up getting the same value for `x` twice as it's random. There's no assurance that the selected set consists of unique values.

You could also express this as:

    $ guild run train x=[1:4] -o random -m 2

or:

    $ guild run train x=range[1:4] -o random -m 2

What is not possible, at least as of 0.7.0.rc11, is to mix grid lists and random functions to perform a true grid search with some values randomly selected.

Here's what does NOT work:

    $ guild run train x=[1:4] y=[5,6] z=[7,8] -o +

Note that the optimizer is `+`. This is the name of the default batch "optimizer" (it's technically not an optimizer as it doesn't attempt to minimize/maximize anything but this what we call it). This overrides Guild's auto detection based on flag values to use an optimizer explicitly.

In this case, Guild will pass along the value of `x` as a string '[1:4'] to your script. I consider this a bug, which is what we can use this issue to track. Guild should see the flag function there and use it to sample values from. In fact, you should be able to specify a list of such flag functions and have those apply to the trial expansion to search over different ranges.

I'm marking this issue as a bug with the caveat that it applies to this last behavior - where Guild passes a flag function as a string when you use `+` for the optimizer.

**Comment by gar1t** [comment]
This is fixed in master and will be available in the followup to 0.7.0.

Specifically, "grid search" (technically the default batch operation) supports uniform and loguniform ranges specified for a flag.

This command starts a normal batch run, which generates two trials -- one for each value of `y`. For each trial, the batch uses a value at random from the uniform distribution over 1 through 4.

```
$ guild run train x=[1:4] y=[1,2] -o +
```

**Comment by gar1t** [comment]
Fix is available in 0.7.0.
