### ISSUE TITLE
local variable and main function?

### ISSUE THREAD

**Issue by arisliang** [guildai/guildai#201]
Noticed the examples are almost all using global variables, top level statements. This is not very good for modularity I suppose, it would be cleaner to wrap variables in main function for example.

Is it possible to do that? Or the variable needs to be at top level for it to be picked up?

**Comment by gar1t** [comment]
The examples are intended to demonstrate a variety of patterns, not in any way to imply programming best practices.

That said, using global variables to define constants is consistent with best practices. Guild's setting of flags in this case redefines those constant values dynamically per run.

If you prefer to not use global variables, I suggest using a command line interface. Guild supports argparse and click APIs for this.

This is the pattern that I use:

``` python
import argparse

def main():
    args = _init_args()
    _train(args)

def _init_args():
    p = argparse.ArgumentParser()
    p.add_argument("--flag1")
    p.add_argument("--flag2")
    return p.parse_args()

def _train(args):
    pass  # TODO: train the model
```

**Comment by arisliang** [comment]
Thanks for the reply. It makes sense then to be able to choose from global variable and argparse.

How about loss and accuracy, etc? Do those variables need to be global variable too? How does guildai pick them up during the run if not?

**Comment by gar1t** [comment]
There are a couple ways - you can simply print them as values to stdout/stderr or log them to TF event files.

This doc explains it:

https://my.guild.ai/t/scalars/160

**Comment by arisliang** [comment]
Brilliant, thanks!
