### ISSUE TITLE
guild view return ImportError: cannot import name 'SharedDataMiddleware' from 'werkzeug.wsgi'

### ISSUE THREAD

**Issue by MislavSag** [guildai/guildai#202]
When I execute guild view command it returns an errorČ
`ImportError: cannot import name 'SharedDataMiddleware' from 'werkzeug.wsgi' (c:\programdata\anaconda3\lib\site-packages\werkzeug\wsgi.py)`

I trued to reinstall werkzeug package but didnćt help.

**Comment by gar1t** [comment]
What version of Guild are you running? This should be resolved by upgrading to the latest prerelease.

    $ pip install guildai --upgrade --pre

**Comment by MislavSag** [comment]
The last version is 0.6.6.?

**Comment by gar1t** [comment]
Yes but the fix for this is in the pre-release of 0.7, which requires upgrading with `--pre`. If you'd prefer to stick with 0.6.6 you need to downgrade the werkzeug package unfortunately.

**Comment by MislavSag** [comment]
It works with --pre version. Thanks
