### ISSUE TITLE
Comparing runs with --strict-cols doesn't show selected columns' values

### ISSUE THREAD

**Issue by vitalwarley** [guildai/guildai#206]
At **Training a second time** section in [Training an Image Classifier](https://guild.ai/docs/start/image-classifier/) tutorial, when running

``guild compare --table --operation mnist --strict-cols =lr,val_acc``

My output shows only this:

```
run       lr  val_acc
ce36d87f      
3cb74a9d  
```

I am using `guildai-0.7.0rc11`, but the issue is also present in 0.6.6.

**Comment by gar1t** [comment]
I see there's a bug in the docs there - `val_acc` should be `val_accuracy`. Keras changed that a while back and we haven't updated the docs.

This commands works for me (I'm running 0.7.0.rc11):

```
$ guild compare --table --operation mnist --strict-cols =lr,val_accuracy
```

I get values for both `lr` and `val_accuracy`.

A couple questions for you:

- What shows up when you run `guild compare --table --operation fashion_mnist_mlp` (difference there is no `--strict-cols` and I changed the op name to match the script more precisely)?

- Do you see the expected operation name, flag values and scalars when you run `guild runs info ce36d87f`?

**Comment by vitalwarley** [comment]
Oops, I noticed that the name for `val_acc` was different, but unfortunately I didn't manage to change it. Sorry. 

I tested all headers, but only these work as expected:

`accuracy  epoch_accuracy  epoch_loss  loss      val_accuracy`

For example:

![2020-07-03-180750_1267x258_scrot](https://user-images.githubusercontent.com/6365065/86497531-6192be00-bd58-11ea-87f1-960e6a77cd8e.png)

Have I missed something?

When I run

`guild compare --table --operation fashion_mnist_ml`

I get 

![2020-07-03-180045_1442x70_scrot](https://user-images.githubusercontent.com/6365065/86497327-a9fdac00-bd57-11ea-9e1e-07b3653ad2a7.png)

It works as expected. And yes, I see the correct output when I run `guild runs info ce36d87f`.

Thanks for the help!

**Comment by gar1t** [comment]
The spec used with any of the column lists in `compare` is a little tricky. A column comes from one of three sources:

- Run attribute
- Run flag
- Run scalar

Guild does not know offhand where to look so you need to tell it. By default, Guild considers a name to be a scalar. If a col is a flag, you need to prefix it with `=`. If it's a run attribute prefix it with `.`.

So your `--strict-cols` spec should be along this line:

```
$ guild compare -t --strict-cols .operation,.started,.time,.status,.label,=batch_size,=dropout,=epochs
```

Though in your case, you might want to use just `-c, --cols` as that includes the core attributes.

```
$ guild compare -t -c =batch_size,=dropout,=epochs
```

**Comment by vitalwarley** [comment]
I thought that the equal sign `=` was just following the `--strict-cols` option. I should have paid more attention to the `guide compare --help`. Sorry for that, and thanks again for all the clarifications!

**Comment by gar1t** [comment]
Of all the many interfaces in Guild, this one makes me the most uneasy :) All excellent questions and I'm glad for the chance to clarify!
