### ISSUE TITLE
Unable to use arrow keys in pdb when using guild

### ISSUE THREAD

**Issue by samedii** [guildai/guildai#221]
When running a command like `guild run train -y` and I have a `pdb.set_trace()` statement in my code somewhere, I will be unable to use the arrow keys to repeat old commands or edit a current command.

If I instead run `python train.py` (the operation points to this file) then this works fine. I am in the same env when doing this.

You can run debugging without guild in some cases but this becomes a problem when
1. the program is outputting many artifacts that you don't want to remove manually
2. or you have a dependency in guild.yml

**Comment by gar1t** [comment]
Set `NO_RUN_OUTPUT=1` and this will start working.

Sample Python file:

```
# test.py
import pdb;pdb.set_trace()
```

Run with output disabled:

```
$ NO_RUN_OUTPUT=1 guild run test.py
```

**Comment by gar1t** [comment]
Incidentally, if you haven't seen [pudb](https://pypi.org/project/pudb/), I recommend trying it. 

Not so incidentally, there's a feature request that Guild support breakpoints so you could run something like `guild run --pdb` or maybe `guild run --break` to drop into a debugger either at the start of your Python script/module or at some specified break point spec.

Personally I prefer just modifying the source with `import pdb; pdb.set_trace()` as I'm used to it but having a `run` option is nice if you don't have convenience access to the source.

**Comment by samedii** [comment]
Nice, thanks for the quick response. I must have missed the email! Thanks for the tip on pudb, I will try it out. Closing as it seems to be a duplicate or closely related to other issues :)
