### ISSUE TITLE
explicit labeling gets appended when a  run with a search is executed

### ISSUE THREAD

**Issue by gryBox** [guildai/guildai#23]
Hi - Currently when one preforms a grid search over parameters  guild automatically inserts the run's parameters into the label.  This _was_ desired behavior before all the parameters had there own columns.    

#### Current Behaviour
`guild run pretrain --label pretrain encoder_lr=[0.001:1.0]  `
Resulting in a label full of noise (duplicated data).
![image](https://user-images.githubusercontent.com/16763201/58398071-3bf59a00-8019-11e9-9705-e4a68d375439.png)

#### Desired Behaviour
`guild run pretrain --label pretrain encoder_lr=[0.001:1.0]  `
![image](https://user-images.githubusercontent.com/16763201/58398167-b58d8800-8019-11e9-8fa2-e52cf31a81af.png)

Ideally the default for label would be the operation i.e. . ~~/code/damsm:~~ pretrain

**Comment by gar1t** [comment]
Yeah, this sounds right - if you specify a label for the run, it should override the default completely.

Look for this fix in the next pre-release.

**Comment by gar1t** [comment]
Teed up for 0.6.4 in d80853b.

**Comment by gar1t** [comment]
This is generally available now so closing. Thanks again for the report!
