### ISSUE TITLE
Tensorboard breaks runs selection due to invalid HORIZONTAL ELLIPSIS character

### ISSUE THREAD

**Issue by guysoft** [guildai/guildai#230]
Hey,
It seem When I try and pick a run on this dialog:
![Screenshot_20200902_154649](https://user-images.githubusercontent.com/325670/91983482-6e219b80-ed34-11ea-8855-609b5b66b699.png)

I get an error in the console:
```
Uncaught DOMException: String contains an invalid character
```
Its related to the character ```…``` (Unicode Character 'HORIZONTAL ELLIPSIS' (U+2026)) that is in my run names

The char is mentioned multiple times in the utilities so I am quite sure guildai generates them.

In the folder  /tmp/guild-tensorboard-rujm2by3, when I rename the folder names tensorboard works correctly.

**Comment by gar1t** [comment]
Thank you for the report and the excellent diagnosis! Yes this is 100% Guild. I'll make sure we fix this for the next release.

In the meantime, as a workaround, you can use the `--run-name-flags` option to list the flag names used to generate the run name. Omit the `dataset` flag so it doesn't appear. You can clear all flags using `guild tensorboard --run-name-flags ''`.

**Comment by guysoft** [comment]
@gar1t Does that commit solve this issue?

**Comment by guysoft** [comment]
Solved by running
```
guild install guildai --pre --upgrade
```
Closing
