### ISSUE TITLE
Guild push fails if venv/.guild does not exist yet

### ISSUE THREAD

**Issue by FelixAbrahamsson** [guildai/guildai#253]
`guild push` crashes when `venv/.guild` does not exist on the remote due to no prior guild op having been run. It fails on `rsync mkdir` with `No such file or directory`.

**Comment by gar1t** [comment]
Thanks for the report! A fix for this is committed and will land in the next release.

**Comment by gar1t** [comment]
This is fixed in 0.7.2.
