### ISSUE TITLE
how to create operations using setup.py?

### ISSUE THREAD

**Issue by kuromt** [guildai/guildai#254]
I am using guildai 0.6.6

```
$ guild --version
guild 0.6.6
```

In my understanding, `guild package` command generate whl file, but the way is difficult to keep consistency between package version and source code. 

Therefore, I want to share guild operations in github using `pip install git+https://github.com/xxx/yyy.git`.

After install the package from github, the module downloaded under `/opt/conda/lib/python3.7/site-packages/mypackage`

In this directory, these files are existing

```
guild.yml  __init__.py  __pycache__  train.py
```

But `guild operarions --installed` doesn't show the operations.

What should I include files in my package?

**Comment by gar1t** [comment]
To support Guild operations this way you need to modify your Python setup scheme to define entry points so that the models are properly exposed.

This guide should help.

https://my.guild.ai/t/guild-packages-with-setup-py/436

I recommend that you upgrade Guild to the latest version by running `pip install guildai --upgrade`.

**Comment by kuromt** [comment]
Thanks!
I will try the way.

**Comment by gar1t** [comment]
If you run into any problems, let us know and we'll help. We're using https://my.guild.ai for support. Just [start a new topic](https://my.guild.ai/new-topic?category=troubleshooting) there.

**Comment by kuromt** [comment]
Thank you for introducing me https://my.guild.ai.

I found typo in https://my.guild.ai/t/guild-packages-with-setup-py/436.

Example of `entry_points` is given an array, but correct syntax is dict type.

This occurs syntax error.

```
setup(
    ...
    entry_points=[
        'guild.models': [
            '__anonymous__=guild.model:PackageModel',
        ],
    ],
    ...
```

I can not find where to report this typo.
Can you fix the typo?
