### ISSUE TITLE
tensorboard<2.3.0 still in requirements.txt for 0.7.1

### ISSUE THREAD

**Issue by FelixAbrahamsson** [guildai/guildai#255]
As far as I understand from [this](https://github.com/guildai/guildai/issues/99) issue the current release should support tensorboard 2.4, but requirements.txt does not seem to be updated.

**Comment by gar1t** [comment]
This was an oversight. You can force an upgrade of the tensorboard and Guild should work fine. This change was committed, in fact actually this time - so the next release will have this. Thanks for pointing this out!
