### ISSUE TITLE
Cannot serialize value dict_keys when parsing flags

### ISSUE THREAD

**Issue by Kaixhin** [guildai/guildai#256]
I'm trying to use a dict as a mapping from keys to classes so that I can easily switch datasets, models, etc. Previously we used an array of strings in `argparse` `choices`, but when I switched to `dict.keys()` I get the following error.

```
WARNING: [import_flags_main] cannot serialize value dict_keys(['gaussian', 'moons', 'mnist', 'kddcup1999']) for flag dataset - coercing to string
ERROR: error in /Project/guild.yml: invalid flag choice data "dict_keys(['gaussian', 'moons', 'mnist', 'kddcup1999'])": expected a list of values or mappings
```

It seems like it tried to do the reasonable thing (convert the dict keys to a list of strings), but failed?

**Comment by Kaixhin** [comment]
I didn't realise that [`dict_keys` is not technically a list](https://stackoverflow.com/questions/16819222/how-to-return-dictionary-keys-as-a-list-in-python), and wrapping it with `list()` is sufficient to solve this problem.

**Comment by gar1t** [comment]
Sorry for the late reply. Glad you were able to resolve this!
