### ISSUE TITLE
 OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed: AutoGraph did convert this function

### ISSUE THREAD

**Issue by melnimr** [guildai/guildai#258]
When trying to run DenseNet121:

```
guild run file.py
```

```
import numpy as np
import pandas as pd
import os
import numpy
import glob
import cv2
from keras.applications.vgg16 import VGG16
from keras.applications import DenseNet121
from keras.models import Sequential
from keras.layers import Flatten, Dense
from imagenet_utils import decode_predictions, preprocess_input

#print(os.listdir("1000_images_each/"))
#weights = './vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5'



folders = glob.glob('./1000_images_each/*')
imagenames_list = []
for folder in folders:
    for f in glob.glob(folder+'/*'):
        imagenames_list.append(f)




def label_img(image):
    word_label = image.split('/')[6]
    if word_label == 'meals':
        return [1,0,0]
    elif word_label == 'meds':
        return [0,1,0]
    elif word_label == 'blood' or word_label =='glucose' :
        return [0,0,1]
   # elif word_label == 'glucose':
   #     return [0,0,0,1]
    #else:
    #    return [0,0,0,0,1]

train = []        



for image in imagenames_list:
    label = label_img(image)
    train.append([np.array(cv2.resize(cv2.imread(image),(224,224))), np.array(label)])
    np.random.shuffle(train)

X = np.array([i[0] for i in train])
X = X/255
Y = np.array([i[1] for i in train])

model = Sequential()
#model.add(DenseNet121(include_top = False, weights = weights, input_shape = (224,224,3)))
model.add(DenseNet121(
   include_top=False,
    weights="imagenet",
    input_tensor=None,
    input_shape=(224,224,3) 
))
model.add(Flatten())
model.add(Dense(4096, activation = 'relu'))
model.add(Dense(4096, activation = 'relu'))
model.add(Dense(4096, activation = 'relu'))
model.add(Dense(3, activation = 'softmax'))
model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])
Fit = model.fit(X, Y, epochs = 20, validation_split = 0.30,batch_size=32)
```

I get:

 OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed: AutoGraph did convert this function

**Comment by gar1t** [comment]
I'm assuming this runs okay with `python file.py`. If not that's the place to start.

I don't see any statements that Guild would interpret as flags, but Guild may be setting a flag value that's throwing the script off. When you run `guild run file.py` are you prompted with any flag values? You can also explicitly check for flag detecting by running `guild run file.py --test-flags`.

If it turns out there's a problem with Guild's auto-detection of flags, you can disable this by running the script as a Guild file operations. Add a file `guild.yml` that looks like this:

``` yaml
# guild.yml

op:
  main: file
```

And run the operation like this:

```
$ guild run op
```

By default Guild does not import flags so this ensures that Guild doesn't attempt to set anything.

**Comment by melnimr** [comment]
Thanks for your followup.

Yes, it does running python3 file.py works fine.

When trying the op option I get:
ModuleNotFoundError: No module named 'pandas'

it looks like it doesn't properly load the environment.

**Comment by gar1t** [comment]
Guild is likely running the operation using a different VM. You can see what Guild is using by running `guild check`.

The best way to control the Python environment is to use a virtual environment. When you run Guild within an activated environment, Guild uses the current Python VM.

To explicitly specify the Python VM for a run command, specify the `GUILD_PYTHON_EXE` environment variable. If you're using a POSIX shell you can set it directly in the command:

    $ GUILD_PYTHON_EXE=python3 guild run op

**Comment by melnimr** [comment]
So I included the libraries needed in the requirments.txt file. I also tried:

```
GUILD_PYTHON_EXE=python3 guild run run_vgg.py
```

but I am still getting the same error:

```
 OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.

```

**Comment by gar1t** [comment]
In that example, you're running the script directly. Could you confirm that you have a Guild file in your project (named `guild.yml`) that looks something like this:

``` yaml
# guild.yml - next to run_vgg.py

vgg:
  main: run_vgg
```

Then run it this way:

```
GUILD_PYTHON_EXE=python3 guild run vgg
```

Guild will not attempt to import any flags in this case so we'll eliminate that as a possible source of issues.

**Comment by melnimr** [comment]
Nice, it works now.

I made sure I include everything in the requirements.txt file.
Also, I did
```
main: run_vgg
```

instead of 
```
main: run_vgg.py
```

plus using the GUILD_PYTHON_EXE option.

**Comment by melnimr** [comment]
Just curious for completeness what is the other option that I had for running it?

**Comment by gar1t** [comment]
Awesome - I'm glad it's working! Sorry for the snags along the way.

I'm not sure what the other option is. The point of running the operation through the Guild file is to control what's imported as flags. By default Guild doesn't import flags for operations defined in a Guild file, whereas Guild imports all flags (or what it thinks are flags) when you run the script directly.

When you run an operation defined in a Guild file it looks like this:

    $ guild run vgg

When you run the script directory it looks like this:

    $ guild run run_vgg.py

**Comment by melnimr** [comment]
Thanks, how can I contribute to this project?

**Comment by gar1t** [comment]
I was going to refer you to the contributors policy but it didn't exist!

[Here you go](https://github.com/guildai/guildai/blob/master/CONTRIBUTING.md).
