### ISSUE TITLE
Pypi create a sdist release or wheel with none-none

### ISSUE THREAD

**Issue by delijati** [guildai/guildai#262]
Hi,

we run multiple time into problem as guildai is only releasing wheels and all wheels are pinned to a python interpreter version -> https://pypi.org/project/guildai/0.7.0/#files has no python3-9 wheel

As guildai has no compiled parts (as far i can see it, and uses no interpreter specific code e.g. await async) it not necessary to pin it to a interpreter version.

Thanks

**Comment by gar1t** [comment]
Guild compiles psutil. This is a holdover from when psutil wheels were not not supported on Windows. We'll pull the psutil compilation and start creating architecture independent wheels.

**Comment by gar1t** [comment]
The latest pre-release (0.7.3.dev4) is now provided as pure Python wheel.

https://pypi.org/project/guildai/0.7.3.dev4/#files

I'm going to close this. If there are still any issues please feel free to re-open.

Thanks a lot for the issue. This was a good improvement I think.

**Comment by delijati** [comment]
thanks  a lot @gar1t
