### ISSUE TITLE
Notebook output is only captured after notebook has finished running

### ISSUE THREAD

**Issue by ngoodger** [guildai/guildai#275]
Please correct me if I am wrong but I believe that the output and scalars are only viewable once the notebook has finished execution.  This is a problem for me at least because I'd like to use notebooks for longer running experiments and want to view the output in tensorboard while the experiment is still running.

I tried redirecting the relevant print statements to stdout as a workaround but that doesn't work.  Looking at the code I think it is because the subprocess.call method does not emit stdout.

**Comment by gar1t** [comment]
Thanks for the report! I creates an issue resolution doc for this:

https://github.com/guildai/issue-resolution/tree/master/275-notebook-output-is-only-captured-after-notebook-has-finished-running

That doc outlines the issue and illustrates how you can accomplish what you're looking for.

It's going to be trick to implement the functionality you're looking for, which relies on Guild's output scalar support. Guild relies on Jupyter commands to execute the notebook at this time and doesn't have access to the output prior to the notebook fully executing. The workaround outlines in the doc above logs scalars explicitly using tensorboardX. While not as convenient certainly as Guild output scalar support, it works well enough and doesn't add a whole lot to your code.

Please let me know what you think of this approach. Thanks again!

**Comment by ngoodger** [comment]
Awesome, thank you!

I had thought about logging to tensorboard but I missed that
> Guild detects scalars logged to TensorBoard summaries
I assumed I would have to run tensorboard separately and wouldn't be able to see the scalars in the Guild View. But I can see scalars and the tensorboard view.  So it works great.

Ultimately it might be nice to delete the explicit tensorboard integration to avoid the "library integration" but it's a minor issue.

Great project!  Really looking forward to continue using it.
