### ISSUE TITLE
Feature request: adding -A, --archive DIR flag to `guild view`

### ISSUE THREAD

**Issue by hkennyv** [guildai/guildai#277]
Hey there,

I don't _think_ this feature exists yet, but this is something that I would strongly benefit from in my workflow. So far, I can view runs that I've previously exported using `guild runs --archive my-runs-dir`. However I would love to extend that functionality and be able to do the same using `guild view` or `guild tensorboard`.

My current workaround is to drag & drop the archived runs into my `guild_home` (that I get from running `guild check`). However, sometimes I have other runs in my `guild_home` that are from a different experiment. It would be awesome to just load up a single directory of archived runs when I need.

I'd be more than happy to contribute myself if you could point me in the right direction as well.

Thanks for all your awesome work!

**Comment by gar1t** [comment]
You're right, this feature doesn't exit across the other commands. I agree it should. The base `guild` command supports a `-H, --home` option, which can be used to specify a different [Guild home](https://my.guild.ai/t/environments/164#guild-home) but this is different from what you're asking. This would be akin to `guild --runs-dir <dir>` or a short form `guild -R <dir>` and would apply to every command.

So the various commands would look like:

```
guild -R my-runs-dir runs list
guild -R my-runs-dir view
guild -R my-runs-dir tensorboard
```

What are you thoughts?

**Comment by gar1t** [comment]
I'm closing this as a dup of #232. This feature will land in the next release. I'll add a comment to that issue to reflect this approach.
