### ISSUE TITLE
Custom SSH port not working

### ISSUE THREAD

**Issue by samedii** [guildai/guildai#28]
Documentation says that it should be possible to specify the port. https://guild.ai/docs/reference/user-config/#ssh-remote

`guild remote status my-ssh`

I get connection timed out on port 22

remotes:
  my-ssh:
    type: ssh
    port: 50000
    user: example
    host: ssh.example.com
    guild-env: /example/my-model

**Comment by samedii** [comment]
No mention of ports in the code but looks like an easy fix. [ssh_util.py](https://github.com/guildai/guildai/blob/master/guild/remotes/ssh_util.py)

Would fix myself and make a PR but spent too much time trying to `make` with several different errors

**Comment by gar1t** [comment]
Thank you! I'll get to that today.

If you could open an issue wrt your `make` errors, that'd be very helpful! I'd like to make it super easy for anyone to build.

**Comment by samedii** [comment]
I did not find any installation instructions because I only looked in the readme. I found it on the homepage now and they worked for me

**Comment by gar1t** [comment]
Ah, good catch! I'll update the README so that's easier people.

**Comment by samedii** [comment]
@gar1t I started on this in a fork: https://github.com/samedii/guildai but got stuck on port not being defined in config like I thought it would be. Hoping you will see an easy solution to that

**Comment by gar1t** [comment]
@samedii This is now supported in the latest release - `0.6.4`. You can upgrade by running `pip install --upgrade guildai`. If that resolves your issue we can close this issue. Thanks again!

**Comment by samedii** [comment]
Thanks! Status is working, having trouble with running but I think that's my config
