### ISSUE TITLE
0.7.3 stop not working with PyTorch data loader

### ISSUE THREAD

**Issue by gar1t** [guildai/guildai#281]
See https://my.guild.ai/t/remote-stop-not-working/584/2 for OP.

cc @samedii

**Comment by samedii** [comment]
Interesting. I do think it used to work in previous versions

**Comment by gar1t** [comment]
I'm able to recreate this with a simple [example](https://github.com/guildai/issue-resolution/tree/master/281-0-7-3-stop-not-working-with-pytorch-data-loader) using `multiprocessing`. Stay tuned for a fix!

**Comment by gar1t** [comment]
The fix for this is committed to master.

**Comment by gar1t** [comment]
Closing - please feel free to open if there there issues!
