### ISSUE TITLE
`guild runs publish` not implemented yet

### ISSUE THREAD

**Issue by hkennyv** [guildai/guildai#288]
Hey there, just wanted to point out it seems like `guild runs publish` does not work yet. The documentation shows [`publish` ](https://my.guild.ai/t/command-runs-publish/109) is a subcommand of `guild run` but it does not seem to reflect the current status of the package.

Guild info:

```
$ guild check
guild_version:             0.7.3
guild_install_location:    /app/venv/lib/python3.9/site-packages/guild
guild_home:                /app/venv/.guild
guild_resource_cache:      /app/venv/.guild/cache/resources
installed_plugins:         config_flags, cpu, dask, disk, exec_script, gpu, ipynb, keras, memory, perf, python_script, queue, skopt
python_version:            3.9.4 (default, Apr  4 2021, 17:42:23) [Clang 12.0.0 (clang-1200.0.32.29)]
python_exe:                /app/venv/bin/python
platform:                  Darwin 20.1.0 arm64
psutil_version:            5.8.0
tensorboard_version:       2.5.0
cuda_version:              not installed
nvidia_smi_version:        not installed
latest_guild_version:      0.7.3
```

**Comment by gar1t** [comment]
Remarkable coincidence - I was fixing this as you opened the issue :)

See a8164da0.

**Comment by gar1t** [comment]
As a workaround, use `guild publish ...` (drop the `runs` part).

Thanks for the report!

**Comment by hkennyv** [comment]
@gar1t wow.. incredible timing :) can we expect this to be part of the next release?

**edit:** found my answer: https://my.guild.ai/t/error-while-publishing-runs/700, thank you!

**Comment by gar1t** [comment]
Yes, for the record here, this will be in 0.7.4.

**Comment by gar1t** [comment]
Closing this - please feel free to reopen if there are issues.
