### ISSUE TITLE
Guild run: command not found

### ISSUE THREAD

**Issue by atemate** [guildai/guildai#289]
Hi! I'm running through the [getting started demo](https://my.guild.ai/t/get-started-with-guild-ai), and it seems that `pip install guildai` installs a wrong package:

```
$ pip install -U guildai
...

$ $ pip show guildai   
Name: guildai
Version: 0.7.3
Summary: Experiment tracking, ML developer tools
Home-page: https://guild.ai
Author: None
Author-email: None
License: Apache 2.0
Location: /plain/github/temp/guild.ai/venv/lib/python3.7/site-packages
Requires: daemonize, numpy, chardet, pkginfo, six, jinja2, setuptools, virtualenv, tensorboard, Pillow, requests, PyYAML, Werkzeug, tabview, psutil, filelock, scikit-optimize, click, scikit-learn
Required-by: 

$ guild run train.py 
guild: unknown script "run"
Try `guild help' for more information.


$ guild             
Usage: guild COMMAND [ARGS]
Run command-line scripts provided by GNU Guile and related programs.

Commands:
  compile              Compile a file.
  disassemble          Disassemble a compiled .go file.
  display-commentary   Display the Commentary section from a file or module.
  doc-snarf            Snarf out documentation from a file.
  help                 Show a brief help message.
  use2dot              Print a module's dependencies in graphviz format.

For help on a specific command, try "guild help COMMAND".

Report guild bugs to bug-guile@gnu.org
GNU Guile home page: <http://www.gnu.org/software/guile/>
General help using GNU software: <http://www.gnu.org/gethelp/>
For complete documentation, run: info '(guile)Using Guile Tools'
```

My env:
```
$ uname -a                
Linux arch 5.12.3-arch1-1 #1 SMP PREEMPT Wed, 12 May 2021 17:54:18 +0000 x86_64 GNU/Linux

$ python --version   
Python 3.7.6
```

What am I doing wrong?

**Comment by gar1t** [comment]
This is an unfortunate collision between the `guild` command and a program of the same name installed by the guile system package.

Here are some workarounds:

- Use Guild in a Python virtual environment. The path should automatically be configured in the environment to look for Python exes before system programs when you active the environment.
- Move the location of pip installed executables (e.g. often `~/.local/bin`) up in the `PATH` env var list so they take precedence over system programs. This is antisocial for the guile programs though.
- If you don't need the guile system package, uninstall it (again, quite antisocial but it's a pragmatic step if you don't need guile)
- Rename the system installed `guild` file (yep, antisocial as heck)
- Rename the Guild AI `guild` script (e.g. to `guildai`)

In practice, most users use Guild inside a Python virtual environment anyway, so the first option is not too controversial. The other options are all bad if you need guile and guild on the same system.

**Comment by atemate** [comment]
OMG it's not pip package `guild` who makes the collision with `guildai`, it's [guile compiler](https://www.gnu.org/software/guile/)!
```
$ yay -Qs guil 
local/guile 2.2.7-1
    Portable, embeddable Scheme implementation written in C
local/guile2.0 2.0.14-5
    Portable, embeddable Scheme implementation written in C
```

**Comment by smao-astro** [comment]
I would like to add one more thing for others have similar issue using a just-installed python virtual environment: if you see your $PATH is configured and `guild` is there but `guild check` does not work (because of conflict with `guile`), maybe try open a new terminal and activate your virtual environment there.
