### ISSUE TITLE
Compatibility with `absl.flags`

### ISSUE THREAD

**Issue by uduse** [guildai/guildai#320]
Say I have a file `hello.py` that's already configured with `absl.flags` (defined an integer flag `n`). Is it possible to use guild to track experiment with different such command line arguments? For example: `guild run hello.py --n 10`. 

So far it seems completely incompatible to me because I can't pass any of the flags defined with `absl.flags` inside `hello.py`.

**Comment by gar1t** [comment]
Flags are specified as *name*=*val* to the `guild` command - they can't be preceded with dashes.

Guild doesn't support flag detection/import from the `absl.flags` framework at this time. You can however explicitly define your flags using a Guild file.

For example, this file defines two flags, foo and bar. These will be specified on the command line as `--foo 123 --bar 456`.

``` yaml
train:
  flags:
    foo: 123
    bar: 456
```

The Guild [docs on flags](https://my.guild.ai/t/flags/42) will give you more details. You want the command line interface in this case.

I could see Guild supporting this `absl` framework at some point. There's a lot of value in having flags imported, especially when there are lots of them. But in the meantime, you can get your flag values passed along to your script by defining them explicitly in the Guild file.

**Comment by uduse** [comment]
@gar1t Thanks for the reply ❤️
