### ISSUE TITLE
some tests use pandas but it is not a requirement

### ISSUE THREAD

**Issue by msarahan** [guildai/guildai#327]
I'm running the tests to validate my changes, and had trouble with batch-skopt3 in particular. I was only able to suss out the root cause by importing guild.ipy separately from the test, which showed an import error for pandas. We probably need some kind of dependency list for the test suite, independent of the requirements of Guild itself.

**Comment by gar1t** [comment]
There's a separate requirements.txt under `guild/tests`.

**Comment by msarahan** [comment]
gah, yeah. Sorry for the noise.
