### ISSUE TITLE
Runs not appearing in guild view due to broken symlinks

### ISSUE THREAD

**Issue by AndrewPaulChester** [guildai/guildai#36]
I don't have lots of detail for this unfortunately, but I have seen two instances of batch runs with broken links. In both cases, the batch run had been terminated part way though, and there were valid links to all child folders that existed, but there were also a broken link to a non-existent child folder. I found this because those batch runs were not showing up in guild view, with the following error on the terminal (I've abbreviated the sections in []):
`ERROR: error processing run data for [e5c]: ValueError('[$GUILDHOME/e5c/a123] does not exist')`
Removing the broken links fixed the problem. This may just be a case of unfortunate timing where I killed the batch between the creation of the link and the creation of the folder.

**Comment by gar1t** [comment]
I believe this is resolved. There was work done in this area and what you're describing sounds like the behavior prior to the change (I don't have the commit where this was fixed handy - but if this comes up again, we'll certainly look more closely).

In the meantime, I created a project to recreate the current behavior:

https://github.com/guildai/issues/tree/master/issue-36

This attempts to recreate the condition you described and shows, when running 0.6.6 (any pre-release version) that Guild View handles the broken link.

That said, this very well may still come up! There may be something special about the cases you observed that's not captured in the issue-36 project. If it does come up again, it would be extremely helpful to get a copy of at least the batch run directory and each of the referenced trials, where they exist.

I'm closing for now with the prospect of reopening if it comes up again.

Thanks for the report!
