### ISSUE TITLE
Easier way to fetch run directory of a specific run?

### ISSUE THREAD

**Issue by uduse** [guildai/guildai#374]
I found myself very frequently needs to `cd` into a the run directory of my latest run to look at the logs. Currently I'm doing `guild runs info` then manually copy the `run_dir` line. Is there an easier way of doing this?

**Comment by gar1t** [comment]
Try `guild open --shell [options] [args]`. This opens a new shell in the first matching run directory.

Note that to return to your original shell, type `exit`. We're using a new shell in this case to make it easy to pop into a run directory, and then return to where you were (along with the correct env state) by exiting the run-specific shell.

**Comment by gar1t** [comment]
You can also use:

    $ cd `guild select --path`

Or better:

    $ pushd `guild select --path`
    $ # do whatever in the run dir
    $ popd

This stuff only works on POSIX friendly shells - so Windows may or may not work depending on the shell you're using.

The `select` command is a general purpose info-query command that you can use in conjunction with other commands with bash command substitution (i.e. backticks or the `$(cmd)` syntax).
