### ISSUE TITLE
Odd quotes in guild labels for numeric flag values passed as string

### ISSUE THREAD

**Issue by AndrewPaulChester** [guildai/guildai#38]
In some of my experiments I get an oddly specific combination of single and double quotes around parameter values in the tensorboard labels: ''"'"'10000'"'"''. This seems to be my fault - it appears to happen when the flags have been auto-collected from argparse, and I've put a string value as the default for an int datatype - e.g.
`parser.add_argument("--replay-buffer-size", type=int, default="10000")`

It also seems like it might be resolved in 0.6.5, but there's just so many different quotes I thought I would mention.

**Comment by gar1t** [comment]
It does indeed appear that this was fixed in 0.6.5. I verified that this behavior is not present in the upcoming 0.6.6.

To recreate the tests, see https://github.com/guildai/issues/tree/master/issue-38. Will closed based on results.

Thank you for the report!
