### ISSUE TITLE
Flag --save-trials not saving anything

### ISSUE THREAD

**Issue by samedii** [guildai/guildai#40]
Very minor issue.

`guild run train problem_train_size=[0.0002,0.0004,0.0008,0.0016,0.0032] --save-trials mixup_semisupervised.csv`

The flag --print-trials is working though so I can pipe that to a file instead

Edit: Nevermind print trials is cut off at the length of the terminal but I can create the csv myself

**Comment by gar1t** [comment]
Thank you for reporting this! This has been fixed for 0.6.6 and is available for preview in 0.6.6.dev4.

**Comment by samedii** [comment]
Nice, I will try it out! :)
