### ISSUE TITLE
Hash of source code in compare

### ISSUE THREAD

**Issue by samedii** [guildai/guildai#41]
This is a feature request. I think it would be helpful if there was a hash of the source code to filter on in compare

**Comment by gar1t** [comment]
Good idea!

Just to confirm I understand what's driving this... You want to see at-a-glance if the source code snapshot has changed across two runs. If you're trying to resolve why results are different between two runs, it's nice to spot if the source has changed - and then use `diff` to investigate further.

Did I get that right?

**Comment by samedii** [comment]
That's exactly it! :) Also for filtering the guild compare --csv results

**Comment by gar1t** [comment]
Ah, interesting. So I can include a run filter for sourcecode hash across all of the run list commands (similar to filter by run status, operation, etc. but this would filter by sourcecode hash).

I think in your case the command might look like:

    $ guild compare --sourcecode-digest abc123

You'd be able to enter a digest prefix to match.

**Comment by gar1t** [comment]
This is teed up for 0.6.6 and available for preview in 0.6.6.dev3 and later.

**Comment by samedii** [comment]
Works great! Thank you!
