### ISSUE TITLE
How to reuse flags from the last run?

### ISSUE THREAD

**Issue by uduse** [guildai/guildai#419]
I found using `guild run -e` extremely helpful since I change many flags for each run. Is it possible to create the editor content based on the flags of a specific run (most of the time the last run in my use case) instead of based on the default flags?

I tried using `guild runs info` and `guild select` to retrieve flags setting from a specific run but couldn't make it work.

**Comment by msarahan** [comment]
I think this may fit under what @gar1t has been working on. He's calling it a "merge" feature, which will allow you to merge flag values and such to your local code. I'll let Garrett comment on whether this is accurate, and if it is applicable, whether it's ready for usage.

**Comment by gar1t** [comment]
You can use the `--proto` option to select a run to use as a "prototype" for a new run. By default this will also use the run's source code - so beware! You can tell Guild to use your working code with the `--force-sourcecode` option. So you should be able to use this:

    $ guild run --proto <run Id with the flags you want> --edit-flags --force-sourcecode

**Comment by uduse** [comment]
I have been using `--proto` for a while now and it's quite convenient. The only problem with that is the `--force-sourcecode` doesn't force a version of the locally installed package. @gar1t [mentioned in the forum](https://my.guild.ai/t/tracking-source-code-that-is-a-python-package/816) that we can use `guild remote` to localhost as a workaround. However, I work on a server with company's proxy and everything gets much more complicated with network things. Other than that, this solution is perfectly enough 👍
