### ISSUE TITLE
Is it possible to get run label during the run?

### ISSUE THREAD

**Issue by uduse** [guildai/guildai#426]
We have `RUN_DIR` and `RUN_ID` but it seems run label isn't passed as an environment variable?

**Comment by msarahan** [comment]
seems like an easy addition. We'll look into it for the next release.

**Comment by msarahan** [comment]
@uduse please check the PR above and verify that it does what you need it to do.

**Comment by uduse** [comment]
@msarahan That's quick 😄 Yes this is what I want. I thought this will be a feature infuturer guild python API though.

**Comment by msarahan** [comment]
I'm afraid I don't understand your comment here. I would expect a python API to make the label available as an attribute on a `Run` object. If there's somewhere else we need to add this, let's talk more. I think it's a good addition to these env vars regardless.

**Comment by gar1t** [comment]
We might want to slow down on this. I'm not sure adding env vars for additional run metadata is a good idea. The env space is something we could theoretically fill up with all sorts of useful run data - but there's a lot of metadata and the env would soon become filled with Guild stuff (def something we should avoid).

@uduse I think this is better provided as either an API, or something as a convention of reading the file `.guild/attrs/label` - which sits alongside all of the other run attributes, which you can read as needed.

The as-of-yet unreleased Guild API is `guild._api` and does have pretty easy support for this.

``` python
from guild import _api as gapi

print(gapi.current_run().get("label"))
```

This interface will not change and we'll always provide `guild._api` even when we promoted this, so you can trust this will work forever.

**Comment by msarahan** [comment]
What I prefer about the env var approach is that it does not assume that guild is available inside the context of a run. In my opinion, we need to keep guild out of the run environment as soon as we can manage, but this proposed change would introduce a new, tighter coupling. It would also introduce a runtime requirement on Python, even if the run had nothing to do with Python.

I guess this is an argument for either providing the env var, or for providing some shorthand standard or shell command for reading the `.guild/attrs/label` file.
