### ISSUE TITLE
Guild View doesn't see loss

### ISSUE THREAD

**Issue by lambdaofgod** [guildai/guildai#44]
I ran train.py experiment from your basic quickstart. 
guild compare returns correct output:

```
run       operation  started              time     status     label  noise     x         step  loss
0b5abf62  train.py   2019-08-09 15:31:50  0:00:00  completed         0.100000  0.100000  0     0.516821
0785ce18  train.py   2019-08-09 15:31:44  0:00:00  completed         0.100000  0.100000  0     0.386353
```
whereas in Guild View compare I don't see metrics (they appear in logs though)

![](https://i.ibb.co/6y2jQd0/guild-view.png)

**Comment by gar1t** [comment]
Thank you! Well get this fixed in the next release (0.6.6)
