### ISSUE TITLE
An example custom plugin 

### ISSUE THREAD

**Issue by obonyojimmy** [guildai/guildai#457]
Am trying to piece together how to extend guild via a custom plugin , some missing pieces that would be helpfull : 

1. bootstrap the plugin folder
2. install and use the plugin

Thank you.

**Comment by gar1t** [comment]
Hello! Guild uses plugins for quite a bit of functionality, not the least of which is the Python support - but there's no example I believe of an externally defined plugin, which would be very helpful to you! Let me see if I can find something or at last put something together that you can work from.

**Comment by gar1t** [comment]
I created a sample plugin [here](https://github.com/guildai/guildai/tree/main/examples/erlang-plugin).

Please take a look at the docs there. This API isn't officially documented so there's not a lot of online docs to help you. I suggest that you post specific questions related to your use case to [my.guild.ai](https://my.guild.ai) (general discussion forums) and we can help there. Depending on what you need to do, there may be other approaches (e.g. custom operations go a long way to implement functionality in Guild - you might not even need a plugin).
