### ISSUE TITLE
How to use data files from local filesystem

### ISSUE THREAD

**Issue by lambdaofgod** [guildai/guildai#46]
I have a problem with using local file as data

I have the following project structure:

```

data/file.csv

experiment.py


```

When I try to run experiment.py, which contains

```
import os
import pandas as pd

DATA_DIR = 'data'
df = pd.read_csv(os.path.join(DATA_DIR, 'file.csv'))
print('shape:', df.shape)

```

I get

> 
> WARNING: Skipping potential source code file /home/kuba/Projects/github_search/data/file.csv because it's too big. To control which source code files are copied, specify sourcecode for topic_model:experiment.
> INFO: [guild] Limiting traceback to user code. Use 'guild --debug run ...' for full stack.
> Traceback (most recent call last):
>   File "/home/kuba/Projects/github_search/experiment.py", line 5, in <module>
>     df = pd.read_csv(os.path.join(DATA_DIR, 'file.csv'))
>   File "/etc/miniconda/envs/ml/lib/python3.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
>     return _read(filepath_or_buffer, kwds)
>   File "/etc/miniconda/envs/ml/lib/python3.7/site-packages/pandas/io/parsers.py", line 429, in _read
>     parser = TextFileReader(filepath_or_buffer, **kwds)
>   File "/etc/miniconda/envs/ml/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
>     self._make_engine(self.engine)
>   File "/etc/miniconda/envs/ml/lib/python3.7/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
>     self._engine = CParserWrapper(self.f, **self.options)
>   File "/etc/miniconda/envs/ml/lib/python3.7/site-packages/pandas/io/parsers.py", line 1853, in __init__
>     self._reader = parsers.TextReader(src, **kwds)
>   File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
>   File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
> FileNotFoundError: [Errno 2] File b'data/file.csv' does not exist: b'data/file.csv'
> 

What's up with that 'skipping potential source code file'? I don't see that covered in any of your examples or documentation.

I tried adding the following to experiment operation:
```

sourcecode:
        - data/file.csv

```

But it still doesn't work.

EDIT:

I've furtherr tried editing guild.yml, and came up with that:

```
- model: topic_model
  description: Simple topic modeling
  operations:
    experiment: experiment
    requires: data
  resources:
    data:
      sources:
      - data/file.csv

```

But it still gives the same error.

**Comment by gar1t** [comment]
My apologies for the frustration. Missing docs for this topic are teed up and will land soon.

In the meantime, here's a project that should clarify things for you:

https://github.com/guildai/issues/tree/master/issue-46

To run any code, just clone that repo and run the documented steps from within the `issue-46` dir.

If you have any further questions, please reply here.

**Comment by antonwnk** [comment]
The link above has been moved to https://github.com/guildai/issue-resolution/tree/master/46-how-to-use-data-files-from-local-filesystem
