### ISSUE TITLE
Guild not preserving nested INI sections as expected

### ISSUE THREAD

**Issue by gar1t** [guildai/guildai#482]
Original issue reported here: https://my.guild.ai/t/resolving-a-nested-ini-cfg-file-changes-its-format/995/3

Issue resolution doc: https://github.com/guildai/issue-resolution/tree/master/my.guild.ai-995-resolving-a-nested-ini-cfg-file-changes-its-format

**Comment by alxmke** [comment]
This issue is resolved in main, an example of the resolution can be found [here](https://github.com/guildai/issue-resolution/blob/master/my.guild.ai-995-resolving-a-nested-ini-cfg-file-changes-its-format/FIX.md)
