### ISSUE TITLE
Feature request: Queue runs (and with modified code)

### ISSUE THREAD

**Issue by samedii** [guildai/guildai#60]
At the moment the workflow the I am looking for is possible by combining:

1. Modify code
2. guild run train --stop-after 0
3. Modify code
4. guild run train --stop-after 0
5. Repeat...
6. Get hash of all runs
7. Queue all runs with guild run --restart hash in bash script

Would be very handy to have a function "queue" that works like a delayed "run"

What you think?

**Comment by gar1t** [comment]
I created an issue project so we can dive into this a bit further:

https://github.com/guildai/issues/tree/master/60-queue-runs-with-modified-code

Feel free to comment here on various points. The issue doc helps to structure any work that comes out of this issue - but it doesn't track the issue status. That's done here.

**Comment by samedii** [comment]
You wrote "here" so I guess you meant answering here and not in the issue project?

The main use case for me is when experiments are left to run without oversight (like over night). Secondly, it would also be a nice tool if your workflow is often that you are running some experiment and meanwhile changing some code that you want to queue up for the next experiment. At the moment I'm solving this by making a commit and then reverting when the currently running experiment is done.

(Referring to the issue project below)
- I am currently doing 1. a lot but it can be a pain for some use cases and it also clogs "guild compare"
- My applications are split into many files. I cannot do number 2 easily. If it was just a single file then sure.
- Interactive/lazy additions of experiments is a nice tool to have. Could also allow us to manually prune batched experiments during grid search

**Comment by samedii** [comment]
This feature has been super useful! Awesome addition!

Wondering what the desired behaviour is when staging operations that rely on each other?
1. guild run train --stage
2. guild run retrain model=... --stage
It might be nice if "retrain" uses 1. by default but I'm not sure. At the moment it is using an older completed run

**Comment by samedii** [comment]
I am not sure stage:ing is working as intended. It seems I get sideeffects from the current state of the code. Have I misunderstood something? I will try to recreate this

The following procedure fails:
1. git checkout master
2. guild run train --stage
3. git checkout nsl
4. guild run train --stage
5. guild run queue

The branch master is working but nsl has a bug that will stop it from running. If I just run guild run train on master, it works. However, when I start the queue after staging in nsl then I get the same bug as I have in nsl.

Also this should fail but does not:
1. git checkout nsl
2. guild run train --stage
3. git checkout master
4. guild run queue

Have I specified the sourcecode incorrectly or something? Any ideas?

Edit: guild diff is showing correct differences in code. The runs seem to be using the current code instead though

**Comment by gar1t** [comment]
Does the code that is failing appear in the `sourcecode` dir of the runs?

    $ guild ls RUN --sourcecode

If it does not, the run will use whatever is in your project directory.

There is no true code isolation in the current scheme. To do that Guild needs to package and install the project code the way it does for remote runs. The currently implementation of staging doesn't support that.

**Comment by samedii** [comment]
This is working well now in --pre!

I noticed that it would be a nice improvement if --stage looked for resources in other staged runs. For example:
1. guild run train
2. guild run retrain unfreeze=all
Where 2. uses the results from 1.

At the moment I have to always specify this manually as it is picking the latest "train" run that finished.

**Comment by gar1t** [comment]
Guild now fully resolves dependencies at the time of staging. I updated https://github.com/guildai/issue-resolution/tree/master/60-queue-runs-with-modified-code with [additional steps](https://github.com/guildai/issue-resolution/tree/master/60-queue-runs-with-modified-code#update-20191229---guild-resolves-upstream-ops-at-stage-time) to show this behavior.

Note that this behavior is pending 0.7.0 (it's available in the current pre-release).

**Comment by gar1t** [comment]
Fix is officially available in 0.7.0. What a great issue - thanks for driving this!
