### ISSUE TITLE
Specifying operation resource in batch run does not work?

### ISSUE THREAD

**Issue by samedii** [guildai/guildai#61]
Guild does not resolve the correct model but picks the latest one.

`guild run retrain model=b212... batch_size=16 learning_rate=[1e-4,1e-3,1e-5]`

Note that `guild run retrain model=b212... batch_size=16 learning_rate=1e-4` does work

**Comment by gar1t** [comment]
Confirmed as a bug. Here's the issue project that recreates it:

https://github.com/guildai/issues/tree/master/61-operation-resource-in-batch-does-not-work

Note that as an interim workaround, Guild uses the latest marked run even in batch trials.

**Comment by gar1t** [comment]
This will be resolved in 0.6.7. An pre-release version with this fix is available now.

**Comment by gar1t** [comment]
Fix is officially available in 0.7.0.
