### ISSUE TITLE
Guild diff against current source code

### ISSUE THREAD

**Issue by samedii** [guildai/guildai#62]
Would be a nice feature to be able to immediately do guild diff against the current code.
At the moment I am doing something like
`guild run train --stop-after 0`
`guild diff 1 X`
`guild runs delete 1`

**Comment by gar1t** [comment]
The following function is available for evaluation in 0.6.7.dev4:

- `diff` has a `--working` option flag that will diff one run to your working source code directory

- `diff` has a `--working-dir` option where you can specify a directory of source to compare to a run

**Comment by samedii** [comment]
Works nicely in preview! Closing
