### ISSUE TITLE
Feature request: "Extra" column for required resource hash

### ISSUE THREAD

**Issue by samedii** [guildai/guildai#63]
Would be nice if the model hash of `guild run retrain model=hash` showed up in `guild compare -e`

**Comment by gar1t** [comment]
Great idea! I have a note to include that in the label as well. These resource values are essentially flag and should be treated that way. I could see a case for just having them in compare without -e - they're just as important as any of the flag vals.

**Comment by gar1t** [comment]
This will be available in 0.6.7. A pre-release version with this feature is available now.

**Comment by samedii** [comment]
Nice! The release works well for `guild run retrain model=hash`.
It would be nice if it also added the column when just doing `guild run retrain` (hash of used model)

**Comment by gar1t** [comment]
Yes that behavior is irritatingly implicit.

The correct behavior would be to select the model prior to the preview so that the value was explicit and not subject to change once displayed to the user.

I'll open a new issue to track this.

**Comment by gar1t** [comment]
The behavior for the pending 0.7 release resolved runs for the preview, shows the run ID.

**Comment by gar1t** [comment]
Fix is now available in 0.7.0.
