### ISSUE TITLE
Use tmux to benefit long SSH remote runs

### ISSUE THREAD

**Issue by wheatdog** [guildai/guildai#65]
Is it possible to wrap current remote SSH commands into a tmux session? I think it would be good for long SSH remote runs in an unstable network connection.

**Comment by gar1t** [comment]
When Guild runs a remote operation, it first starts the operation on the remote server as a background process. Guild then watches that operation so you can see its output. However, the operation continues to run even if Guild is disconnected. E.g. you can type `Ctrl-c` after the remote operation has started and the operation continues to run.

Guild uses the `watch` command for this. You can do it yourself this way:

```
$ guild run train --background   # runs operation in background
$ guild watch  # watch background operation output - Ctrl-c doesn't kill operation
```

**Comment by wheatdog** [comment]
Oops. Sorry, I didn't know that feature. I'll close the issue. Thanks!
