### ISSUE TITLE
Feature request: flag to not save run

### ISSUE THREAD

**Issue by FelixAbrahamsson** [guildai/guildai#68]
I often test my code with guild and delete the run immediately afterwards. I would really appreciate a flag to guild run to not save the run.

**Comment by gar1t** [comment]
You can use the `--run-dir` option to tell Guild to use a temporary run directory. This will prevent that run from showing up in the runs list. You can re-use this run directory if you want - Guild simply overwrites the contents are needed - it does not clear the directory first. If you want a clean directory, just delete the temp dir or specify a new one.

E.g.

    $ guild run train --run-dir /tmp/train-dev
    $ guild runs  # ^ run won't appear in list

    # list all files associated with the run
    $ find /tmp/train-dev

    $ <edit your project>

    # delete temp run dir (optional, only if you want a clean dir)
    $ rm -rf /tmp/train-dev

    # run again after changes
    $ guild run train --run-dir /tmp/train-dev

**Comment by FelixAbrahamsson** [comment]
That's a neat workaround, thanks! Better than cluttering the api with more flags I think :)
