### ISSUE TITLE
Guild compare saving to csv file throws error

### ISSUE THREAD

**Issue by awoerner92** [guildai/guildai#82]
In the newest release 0.6.6, the command ```guild compare --csv > RUNS.csv``` from the docs throws the error `guild: --csv option requires an argument`. 
Changing the command to ```guild compare --csv RUNS.csv``` and thereby providing the filename to the option returns the error `TypeError: a bytes-like object is required, not 'str'`.

For reproducing this error, I used the code from the Quick Start. Guild has been installed via pip on python 3.7.

Note: After checking the changes between 0.6.5 and 0.6.6, I tried executing `guild compare --csv - > RUNS.csv`. This works like a charm! :)

Thank you for the amazing work you did by developing this package!

**Comment by gar1t** [comment]
Thank you! We'll get this one fixed for the next release (0.7).

**Comment by Alexander-Schiendorfer** [comment]
Hi, I just stumbled across the same problem.
Will 
`guild compare --csv - > RUNS.csv` be the suggested workaround or will you go for the `guild compare --csv RUNS.csv` option?

**Comment by gar1t** [comment]
To generate the CSV file, I suggest running:

```
guild compare --csv RUNS.csv
```

The other form does the same thing but takes longer to type :)

Btw I suggest running the pre-release of 0.7 - you can install it by running `pip install guildai --upgrade --pre`.

**Comment by gar1t** [comment]
Fix is available in 0.7.0. Thanks again!
