### ISSUE TITLE
Feature request: allow ssh connection via proxy

### ISSUE THREAD

**Issue by awoerner92** [guildai/guildai#83]
Hi @gar1t,
how do you feel about integrating the option to connect to a SSH remote via a proxy? Since we have our remotes in a private AWS subnet which is only accessible via a VPN, we require a proxy server in order to connect to the remotes. 
Code for this already exists, however I would like to align with you first, if this is something that you also find helpful :)

Cheers
Alex

**Comment by gar1t** [comment]
Absolutely - that would be great! Is this something you could present via a pull request?

**Comment by awoerner92** [comment]
Yes, I will publish the changes in a pull request.

**Comment by awoerner92** [comment]
I added the PR. @gar1t what do you think?

**Comment by gar1t** [comment]
Sorry for the delay - looks great!

**Comment by awoerner92** [comment]
Great, thank you!
