### ISSUE TITLE
Usage of guild.ai and exporting of models

### ISSUE THREAD

**Issue by joshy** [guildai/guildai#96]
Hi Garrett,

very cool project, thanks a lot for that. I am currently switching from jupyter lab to guild.ai for better organizing experiments. A few things I have noticed:
  * I lookup quite often where the runs dir is because it is hidden and I want to see artifacts created (e.g. confusion matrix). If it could be set to a directory (maybe with guild.yml) would be useful for me
  * I have trained and tested a model and now I want to export it to run on other data. What is the way to export the model? Couldn't find something in the documentation (I don't want to publish it to pypi) 

Thanks a lot and with best regards,
Joshy

**Comment by gar1t** [comment]
Hi and thanks for the kind words!

Guild supports a few ways to get faster access to the files for a run.

The most direct path to what you're asking for would be to use the `--run-dir` option to the `run` command. Use this to tell Guild where to generate the run. Note however that the run won't show up in any listing as it's outside of the runs dir (which as you've seen is `.guild/runs` in the active environment).

I tend to use the `open` command, which uses your system's configured programs to open/view runs and run files. E.g. `guild open [RUN]` will open the system file explorer for `RUN` - or the latest run if you omit the argument.

You can similarly open specific files using the `-p` or `--path` option.

This has the advantage of keeping the runs you generate within the environment.

For cases where you're just re-running an operation to generate files to examine, the `--run-dir` option is handy as you can just overwite files in a single location. Once you're happy with the behavior, you can generate runs in the normal way. I think of this as a development mode.

Regarding your second question, if you simply want to export the run to a directory - where presumably you'll handle the copy/deployment from there without Guild - use the `export` command. You can export one or more runs using the standard run selection filters. This will copy (or move if you use the `--move` option) the selected runs to the directory you specify. Each run is stored in that directory under it's unique run ID.

On the other hand, if you want to a Guild operation to use a trained model, you can setup a dependency in the Guild file along this line:

```
train:
  description: Train a model

run-on-other-data:
  description: Use trained model to do something with data
  requires:
    - operation: train
```

When you run `run-on-other-data` (of course a made up name - whatever makes sense in your case) Guild will create links to the files from the latest non-error `train` operation in the `run-on-other-data` run directory. There you can use the trained model for whatever task and capture that work as a run, like any other.

At Guild AI we use downstream operations like this for a lot of things - even serving a file as a long running operation. That might seem a little weird, but in cases where you want to treat a *serve* as a trackable experiment (surprisingly useful as any given model ought to be measured during inference as well as training) it's very handy.

You could also think of these downstream operations (e.g. `run-on-other-data` above) as a way to package and deploy a model. E.g. if you need to do some work on a trained model before copying it to a location for your ops team, treat that as an operation - e.g. `deploy`.

Or, short of the suggestions above, you can use `cat` to copy a file using IO indirection:

```
$ guild cat [RUN] -p PATH_TO_YOUR_MODEL > ~/deployed-models/SOME_MODEL_FILE
```

**Comment by joshy** [comment]
Hi Garret,

thanks for your explanations! I have somehow missed the `open` command.
