### ISSUE TITLE
git init windows : The specified file is not found

### ISSUE THREAD

**Issue by pie-leroy** [guildai/guildai#97]
Hi,
when i try to make a "guild init" from windows on python i get this error :

"The specified file is not found"
It comes from this command line "subprocess.py", line 1019, in _execute_child

and at line 1019 :

`
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                                         # no special security
                                         None, None,
                                         int(not close_fds),
                                         creationflags,
                                         env,
                                         os.fspath(cwd) if cwd is not None else None,
                                         startupinfo)`

**Comment by gar1t** [comment]
Hello and thanks for the report! I'm sorry you're running into this.

Could you provide the whole traceback?

Also, could you run this code from a Python prompt?

```
import subprocess
subprocess.call("dir")
```

Thanks!

**Comment by pie-leroy** [comment]
I have the same error when i run `guild init` and your code :

`
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-43f1c4157457> in <module>
      1 import subprocess
----> 2 subprocess.call("dir")

c:\users\USER\appdata\local\continuum\miniconda3\envs\formation-deeplearning\lib\subprocess.py in call(timeout, *popenargs, **kwargs)
    285     retcode = call(["ls", "-l"])
    286     """
--> 287     with Popen(*popenargs, **kwargs) as p:
    288         try:
    289             return p.wait(timeout=timeout)

c:\users\USER\appdata\local\continuum\miniconda3\envs\formation-deeplearning\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    727                                 c2pread, c2pwrite,
    728                                 errread, errwrite,
--> 729                                 restore_signals, start_new_session)
    730         except:
    731             # Cleanup if the child failed starting.

c:\users\USER\appdata\local\continuum\miniconda3\envs\formation-deeplearning\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1015                                          env,
   1016                                          os.fspath(cwd) if cwd is not None else None,
-> 1017                                          startupinfo)
   1018             finally:
   1019                 # Child is launched. Close the parent's copy of those pipe

FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
`

**Comment by gar1t** [comment]
This looks like a bug in Guild - adding label.

As a workaround, you can use conda or virtualenv to create a standard virtual environment to use Guild. `guild init` is simply a convenience (when it works ;) for using `virtualenv`.

**Comment by pie-leroy** [comment]
Ok thank you for your reponse.
And when i make a "guild view" how can i specify a specific folder ?

I wanted to make a guild init for specify the root dir

**Comment by gar1t** [comment]
Once you've created an environment (using `guild init` when it works, or `conda` or `virtualenv` otherwise) you need to activate that environment. All Guild commands are applicable to the currently activated environment.

You can check to see which environment Guild is using by running `guild check`.

**Comment by pie-leroy** [comment]
and how can i change the tensorboard default dir ? Is it possible ? 

Thank you for your work !

**Comment by gar1t** [comment]
When you run `guild tensorboard` Guild full manages the log dir. If you want to run TensorBoard on a specific log dir, I suggest running `tensorboard` directly. That said, you might not need to. When you run `guild tensorboard` Guild dynamically adds and removes runs based on the filter criteria that you specify.

E.g. if you want to view a single run, use `guild tensorboard RUN_ID`. If you want to view only runs for a specific operation, `guild tensorboard -o OPERATION`.

Try `guild tensorboard --help` for a list of options.

**Comment by gar1t** [comment]
The Windows related init issue has been fixed and is pending release in 0.7.0.

**Comment by gar1t** [comment]
The fix is now generally available in 0.7.0. If this is still an issue, please re-open and we'll sort it out. Thanks again for the report.
